// Seed data for the front of the pipeline: inquiries, the plant's technical assessments, and the
// mock mailbox that stands in for the proposed Gmail connector.
//
// The set is deliberately shaped to show that an inquiry is not a promise of a quotation. Of the
// eleven seeded here: four became quotations that were accepted and turned into orders, one went
// straight to a sales order on the customer's own PO, one was declined, one was lost to a
// competitor, one is still sitting with the plant, one has only just arrived, and one is an
// assessment waiting on a quotation to be drafted. That spread is the point of the module.

import type { CustomerInquiry, MailMessage, TechnicalAssessment } from "./types";

export const INQUIRIES: CustomerInquiry[] = [
  {
    id: "INQ-3101",
    customerId: "CUST-006",
    receivedDate: "2026-04-08",
    source: "email",
    subject: "Request for quotation — purse seine netting, two sizes",
    requirement:
      "Nylon braided net, No.120 210/22x16 and No.84 210/16x16, both 3-1/2\" stretched mesh, 122MD x 50FL. Approx 5 pcs each. Please advise price and lead time.",
    status: "quoted",
    assignedTo: "Grace Tan",
    forwardedDate: "2026-04-08",
    attachments: [
      { id: "a1", name: "RFQ-WestCoast-Apr2026.pdf", origin: "Customer email", uploadedBy: "Grace Tan", date: "2026-04-08" },
      { id: "a2", name: "Plant-costing-INQ-3101.xlsx", origin: "Plant reply", uploadedBy: "Ramon Dela Cruz", date: "2026-04-10" },
    ],
    assessmentId: "TA-4101",
    quotationId: "PI-34101",
  },
  {
    id: "INQ-3102",
    customerId: "CUST-001",
    receivedDate: "2026-07-30",
    source: "email",
    subject: "PO attached — repeat order, agreed pricing",
    requirement:
      "Repeat of last season's order. Customer has issued their own PO with their part numbers and previously agreed prices. No quotation required, they only need order confirmation and shipping dates.",
    status: "direct_order",
    assignedTo: "Grace Tan",
    closeReason: "Customer issued PO PO-88231 with agreed pricing; no proforma required.",
    attachments: [
      { id: "a1", name: "PO-88231-KTI.pdf", origin: "Customer email", uploadedBy: "Grace Tan", date: "2026-07-30" },
    ],
    salesOrderId: "SO-2202",
  },
  {
    id: "INQ-3103",
    customerId: "CUST-003",
    receivedDate: "2026-07-18",
    source: "email",
    subject: "Request for quotation — trawl and cage net replacement",
    requirement:
      "No.72 210/14x16 and No.42 250/08x16, 3-1/2\" and 8\" stretched mesh respectively. 5 pcs of the first, 10 of the second. Standard export packing.",
    status: "quoted",
    assignedTo: "Marcus Reyes",
    forwardedDate: "2026-07-18",
    attachments: [
      { id: "a1", name: "RFQ-Samudra-Jul2026.pdf", origin: "Customer email", uploadedBy: "Marcus Reyes", date: "2026-07-18" },
    ],
    quotationId: "PI-34102",
  },
  {
    id: "INQ-3104",
    customerId: "CUST-004",
    receivedDate: "2026-06-28",
    source: "email",
    subject: "First order — cage net and lacing twine",
    requirement:
      "No.84 210/16x16 3-1/2\" stretched net, 6 pcs, plus 300 kg tarred lacing twine. First order for this account, credit terms to confirm.",
    status: "quoted",
    assignedTo: "Grace Tan",
    forwardedDate: "2026-06-28",
    attachments: [
      { id: "a1", name: "RFQ-GoldenReef-Jun2026.pdf", origin: "Customer email", uploadedBy: "Grace Tan", date: "2026-06-28" },
      { id: "a2", name: "Plant-costing-INQ-3104.xlsx", origin: "Plant reply", uploadedBy: "Ramon Dela Cruz", date: "2026-07-01" },
    ],
    assessmentId: "TA-4102",
    quotationId: "PI-34103",
  },
  {
    id: "INQ-3105",
    customerId: "CUST-002",
    receivedDate: "2026-07-25",
    source: "email",
    subject: "Additional order — Hi-Ex cage netting",
    requirement:
      "No.96 250/20x16, 5\" stretched mesh, 15MD x 120FL. Quantity 6 pcs for a new site. Separate from the order already in production.",
    status: "quoted",
    assignedTo: "Marcus Reyes",
    forwardedDate: "2026-07-25",
    attachments: [
      { id: "a1", name: "RFQ-Nordfisk-Jul2026.pdf", origin: "Customer email", uploadedBy: "Marcus Reyes", date: "2026-07-25" },
    ],
    quotationId: "PI-34112",
  },
  {
    id: "INQ-3106",
    customerId: "CUST-005",
    receivedDate: "2026-04-25",
    source: "email",
    subject: "Request for quotation — trawl replacement panel",
    requirement: "No.72 210/14x16, 3-1/2\" stretched mesh, 122MD x 50FL. 4 pcs. Standard specification, repeat item.",
    status: "quoted",
    assignedTo: "Grace Tan",
    forwardedDate: "2026-04-25",
    attachments: [],
    quotationId: "PI-34105",
  },
  {
    id: "INQ-3107",
    customerId: "CUST-007",
    receivedDate: "2026-08-04",
    source: "email",
    subject: "New enquiry — cage netting for expansion site",
    requirement:
      "Customer is expanding to a second cage site and wants cage netting costed. Mesh depth not yet supplied — asked what information the plant needs.",
    status: "forwarded_to_plant",
    assignedTo: "Grace Tan",
    forwardedDate: "2026-08-05",
    attachments: [],
    assessmentId: "TA-4103",
  },
  {
    id: "INQ-3108",
    customerId: "CUST-011",
    receivedDate: "2026-06-01",
    source: "agent",
    subject: "Request for quotation — trawl replacement panel",
    requirement: "No.72 210/14x16, 3-1/2\" stretched mesh. 3 pcs. Customer wanted delivery within 3 weeks.",
    status: "lost",
    assignedTo: "Miguel Santos",
    closeReason: "Quoted, but customer awarded to a local supplier on lead time. Our 8 weeks against their 3.",
    attachments: [],
    quotationId: "PI-34114",
  },
  {
    id: "INQ-3109",
    customerId: "CUST-016",
    receivedDate: "2026-07-10",
    source: "email",
    subject: "Enquiry: monofilament gill netting",
    requirement: "Monofilament gill net, 250 pcs. Very small diameter mono, well below our usual range.",
    status: "no_quote",
    assignedTo: "Grace Tan",
    closeReason: "Outside our production range. Referred the customer to a mono specialist rather than quoting.",
    attachments: [],
  },
  {
    id: "INQ-3110",
    customerId: "CUST-003",
    receivedDate: "2026-08-09",
    source: "email",
    subject: "New enquiry — Q4 replenishment",
    requirement: "Customer flagged a further order to follow their current one, no specification yet. Just arrived.",
    status: "new",
    assignedTo: "Marcus Reyes",
    attachments: [],
  },
  {
    id: "INQ-3111",
    customerId: "CUST-004",
    receivedDate: "2026-08-02",
    source: "email",
    subject: "Second enquiry — lighter Hi-Ex net",
    requirement:
      "Golden Reef's second enquiry while their first order is still in Deposit. No.42 250/08x16, 8\" mesh. Customer asked whether a lighter twine is possible to reduce cost.",
    status: "assessment_received",
    assignedTo: "Grace Tan",
    forwardedDate: "2026-08-02",
    attachments: [
      { id: "a1", name: "Cage-spec-sketch-2.pdf", origin: "Customer email", uploadedBy: "Grace Tan", date: "2026-08-02" },
    ],
    assessmentId: "TA-4104",
  },
];

export const TECHNICAL_ASSESSMENTS: TechnicalAssessment[] = [
  {
    id: "TA-4101",
    inquiryId: "INQ-3101",
    customerId: "CUST-006",
    requestedDate: "2026-04-08",
    respondedDate: "2026-04-10",
    verdict: "feasible",
    assessedBy: "Ramon Dela Cruz",
    plantRemarks:
      "Both specs are standard for us and the tooling is already set. No substitutions needed. Costing below is at current nylon pricing.",
    leadTimeNote: "8 weeks from receipt of deposit for both sizes together.",
    lines: [
      {
        id: "l1",
        specCode: "N-1596",
        description: 'NO.120(210/22x16) 3-1/2"STR 122MD x 50FL',
        specification: "NYLON BRAIDED NET SK DSTB DWS PREDYED BLACK AND TARRED",
        material: "Nylon",
        netType: "Braided Net",
        weightPerPc: 241.5,
        qtyPcs: 5,
        costPerKg: 11.60,
      },
      {
        id: "l2",
        specCode: "N-1594",
        description: 'NO.84(210/16x16) 3-1/2"STR 122MD x 50FL',
        specification: "NYLON BRAIDED NET SK DSTB DWS PREDYED BLACK AND TARRED",
        material: "Nylon",
        netType: "Braided Net",
        weightPerPc: 164.85,
        qtyPcs: 5,
        costPerKg: 11.00,
      },
    ],
    quotationId: "PI-34101",
  },
  {
    id: "TA-4102",
    inquiryId: "INQ-3104",
    customerId: "CUST-004",
    requestedDate: "2026-06-28",
    respondedDate: "2026-07-01",
    verdict: "feasible",
    assessedBy: "Ramon Dela Cruz",
    plantRemarks:
      "Standard spec, tooling already set. Twine quantity confirmed against the net's own lacing requirement plus a working margin.",
    leadTimeNote: "8 weeks from receipt of deposit.",
    lines: [
      {
        id: "l1",
        specCode: "N-1594",
        description: 'NO.84(210/16x16) 3-1/2"STR 122MD x 50FL',
        specification: "NYLON BRAIDED NET SK DSTB DWS PREDYED BLACK AND TARRED",
        material: "Nylon",
        netType: "Braided Net",
        weightPerPc: 164.85,
        qtyPcs: 6,
        costPerKg: 11.00,
      },
      {
        id: "l2",
        specCode: "T-2201",
        description: "H-EX LACING TWINE, TARRED, 6MM",
        specification: "TARRED HI-EX LACING TWINE",
        material: "Hi-Ex",
        netType: "Twine",
        weightPerPc: 1,
        qtyPcs: 300,
        costPerKg: 5.10,
      },
    ],
    quotationId: "PI-34103",
  },
  {
    id: "TA-4103",
    inquiryId: "INQ-3107",
    customerId: "CUST-007",
    requestedDate: "2026-08-05",
    verdict: "pending",
    assessedBy: "—",
    plantRemarks: "",
    lines: [],
  },
  {
    id: "TA-4104",
    inquiryId: "INQ-3111",
    customerId: "CUST-004",
    requestedDate: "2026-08-02",
    respondedDate: "2026-08-06",
    verdict: "feasible_with_changes",
    assessedBy: "Ramon Dela Cruz",
    plantRemarks:
      "The lighter twine the customer asked about would not hold at 8\" mesh under cage load. Recommend staying at 250/08x16. Costed below on that basis. If they insist on lighter, we would not warrant it.",
    leadTimeNote: "8 weeks. Hi-Ex stock is committed until early September.",
    lines: [
      {
        id: "l1",
        specCode: "H-1642",
        description: 'NO.42(250/08x16) 8"STR 50MD x 120FL',
        specification: "HI-EX BRAIDED NET SK DSTB DWS PREDYED BLACK AND TARRED",
        material: "Hi-Ex",
        netType: "Braided Net",
        weightPerPc: 33.9,
        qtyPcs: 10,
        costPerKg: 14.50,
        note: "Substituted back to 250/08x16 from the customer's lighter request.",
      },
    ],
  },
];

// -------------------------------------------------------------------------
// Mock mailbox. See the MailMessage type note: none of this touches a real
// mailbox, it exists so the proposed flow can be demonstrated.
// -------------------------------------------------------------------------

export const MAIL_MESSAGES: MailMessage[] = [
  {
    id: "M-301",
    folder: "inbox",
    from: "dcruz@wcmarinesupply.com",
    to: "sales@fortunenet.com.ph",
    subject: "Possible third order — Q1 2027",
    body: "Hi Grace,\n\nWe're planning ahead for Q1 next year and may have a third order coming your way, similar spec to the last two. Nothing firm yet, just flagging it so it's on your radar.\n\nDan",
    date: "2026-08-09T16:40:00",
    read: false,
    suggestedCustomerId: "CUST-006",
    attachmentNames: [],
  },
  {
    id: "M-302",
    folder: "inbox",
    from: "purchase@ktigroup.co.kr",
    to: "sales@fortunenet.com.ph",
    subject: "PO 88231 — repeat order",
    body: "Hello Grace,\n\nPlease find our PO attached for the repeat order, same specification and pricing as our last shipment. No quotation needed on our side, we just need your order confirmation and the shipping date.\n\nBest regards,\nKevin Park",
    date: "2026-07-30T07:45:00",
    read: true,
    suggestedCustomerId: "CUST-001",
    attachmentNames: ["PO-88231.pdf"],
  },
  {
    id: "M-303",
    folder: "inbox",
    from: "ingrid.solberg@nordfisk.no",
    to: "sales@fortunenet.com.ph",
    subject: "Question on mesh depth tolerance",
    body: "Hi,\n\nBefore we place the next order, what tolerance do you hold on mesh depth after depth-way stretching? Our inspector flagged this on the last delivery.\n\nThanks,\nNordfisk Trading AS",
    date: "2026-08-06T10:15:00",
    read: true,
    suggestedCustomerId: "CUST-002",
    attachmentNames: [],
  },
  {
    id: "M-304",
    folder: "sent",
    from: "sales@fortunenet.com.ph",
    to: "planta@fortunenet.com.ph",
    subject: "FWD: New enquiry — cage netting for expansion site — INQ-3107",
    body: "Forwarding for feasibility and costing. Customer has not given mesh depth yet — please advise what you need from them before we can quote.",
    date: "2026-08-05T09:30:00",
    read: true,
    linkedInquiryId: "INQ-3107",
    attachmentNames: [],
  },
  {
    id: "M-305",
    folder: "plant_reply",
    from: "planta@fortunenet.com.ph",
    to: "sales@fortunenet.com.ph",
    subject: "RE: Second enquiry — lighter Hi-Ex net — INQ-3111",
    body: "Grace,\n\nThe lighter twine will not hold at 8\" mesh under cage load. Recommend staying with 250/08x16. Costing attached on that basis, 14.50 per kg, 33.9 kg per piece.\n\nLead time 8 weeks, Hi-Ex stock is committed until early September.\n\nRamon",
    date: "2026-08-06T14:05:00",
    read: true,
    linkedInquiryId: "INQ-3111",
    linkedAssessmentId: "TA-4104",
    attachmentNames: ["Plant-costing-INQ-3111.xlsx"],
  },
];
