import type {
  RoleInfo,
  Customer,
  ItemMaster,
  LookupTable,
  PricingRule,
  Quotation,
  SalesOrder,
  PaymentRecord,
  CommercialInvoice,
  DocRecord,
  ApprovalRequest,
  ActivityEntry,
  StageRecord,
  OrderStage,
} from "./types";
import { ORDER_STAGES } from "./types";

export const ROLES: RoleInfo[] = [
  {
    id: "sales_rep",
    label: "Sales Representative",
    department: "Sales",
    description: "Handles inquiries, quotations, and customer follow-up.",
  },
  {
    id: "sales_manager",
    label: "Sales Manager",
    department: "Sales",
    description: "Approves quotations, discounts, and order verification.",
  },
  {
    id: "factory_technical",
    label: "Factory Technical Team",
    department: "Technical",
    description: "Assesses feasibility and confirms production specs.",
  },
  {
    id: "finance",
    label: "Finance / Accounting",
    department: "Finance",
    description: "Verifies deposits, balances, and releases financial clearance.",
  },
  {
    id: "logistics",
    label: "Exportation / Logistics",
    department: "Logistics",
    description: "Books shipments and manages loading documentation.",
  },
  {
    id: "management",
    label: "Management",
    department: "Executive",
    description: "Oversight across the full order lifecycle.",
  },
  {
    id: "admin",
    label: "System Administrator",
    department: "Admin",
    description: "Full visibility for demonstration purposes.",
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: "CUST-001",
    name: "KTI Company Limited",
    consignee: "KTI Company Limited",
    country: "South Korea",
    address: "1503-8, Dadae-Dong, 49486 Saha-Gu, Busan, Korea",
    contactPerson: "Mr. Kevin Park",
    email: "purchase@ktigroup.co.kr",
    phone: "+82 51 264 0024",
    defaultPaymentTerms: "20% deposit, 80% before shipment",
    defaultCurrency: "USD",
    totalOrders: 14,
    totalValueUSD: 1284300,
    outstandingBalanceUSD: 146940.26,
    since: "2019-03-11",
    letterhead: "FORTUNE NET & TWINE MFG. CORP.",
    agent: "HOUSE ACCOUNT",
  },
  {
    id: "CUST-002",
    name: "Nordfisk Trading AS",
    consignee: "Nordfisk Trading AS",
    country: "Norway",
    address: "Skolegata 14, 6003 Ålesund, Norway",
    contactPerson: "Ms. Ingrid Solberg",
    email: "ingrid.solberg@nordfisk.no",
    phone: "+47 70 12 55 40",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 6,
    totalValueUSD: 402100,
    outstandingBalanceUSD: 0,
    since: "2021-06-02",
  },
  {
    id: "CUST-003",
    name: "PT Samudra Jaring Nusantara",
    consignee: "PT Samudra Jaring Nusantara",
    country: "Indonesia",
    address: "Jl. Perikanan No. 22, Muara Baru, Jakarta Utara",
    contactPerson: "Mr. Budi Hartono",
    email: "budi.hartono@samudrajaring.co.id",
    phone: "+62 21 6660 8812",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 9,
    totalValueUSD: 587250,
    outstandingBalanceUSD: 58210.4,
    since: "2020-01-19",
  },
  {
    id: "CUST-004",
    name: "Golden Reef Fisheries Ltd.",
    consignee: "Golden Reef Fisheries Ltd. / c/o Chittagong Freight Fwd.",
    country: "Bangladesh",
    address: "Agrabad Commercial Area, Chittagong 4100",
    contactPerson: "Mr. Rafiq Ahmed",
    email: "rafiq@goldenreef.com.bd",
    phone: "+880 31 251 4402",
    defaultPaymentTerms: "40% DP, 60% before loading",
    defaultCurrency: "USD",
    totalOrders: 4,
    totalValueUSD: 198400,
    outstandingBalanceUSD: 71460,
    since: "2023-02-14",
  },
  {
    id: "CUST-005",
    name: "Pacífico Redes S.A. de C.V.",
    consignee: "Pacífico Redes S.A. de C.V.",
    country: "Mexico",
    address: "Blvd. Marina Sur 341, Mazatlán, Sinaloa",
    contactPerson: "Sr. Alejandro Ruiz",
    email: "aruiz@pacificoredes.mx",
    phone: "+52 669 981 2230",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 3,
    totalValueUSD: 121600,
    outstandingBalanceUSD: 0,
    since: "2024-05-08",
  },
  {
    id: "CUST-006",
    name: "West Coast Marine Supply Inc.",
    consignee: "West Coast Marine Supply Inc.",
    country: "United States",
    address: "1180 Fisherman's Wharf Rd, San Pedro, CA 90731",
    contactPerson: "Mr. Daniel Cruz",
    email: "dcruz@wcmarinesupply.com",
    phone: "+1 310 555 0148",
    defaultPaymentTerms: "50% DP, 50% before loading",
    defaultCurrency: "USD",
    totalOrders: 11,
    totalValueUSD: 843900,
    outstandingBalanceUSD: 22150,
    since: "2018-09-27",
  },
  {
    id: "CUST-007",
    name: "Senegal Peche Atlantique",
    consignee: "Senegal Peche Atlantique",
    country: "Senegal",
    address: "Route de la Corniche, Dakar",
    contactPerson: "M. Ousmane Diallo",
    email: "o.diallo@pecheatlantique.sn",
    phone: "+221 33 842 1190",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 2,
    totalValueUSD: 76800,
    outstandingBalanceUSD: 53760,
    since: "2025-01-30",
  },
  // ---- Imported from the export client master (real accounts, no order history in this prototype) ----
  { id: "CUST-008", name: "Alphatex", consignee: "Alphatex", country: "France", address: "Le Gite Bernard, 76490 Saint Wandrille Rancon, France", contactPerson: "Mr. Paul Lemonnier", email: "china.office2@alphatex.eu", phone: "+003 323 270 4265", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Paul Lemonnier", email: "china.office2@alphatex.eu", isPrimary: true }, { id: "c2", name: "Mr. Romain Chevalier" }, { id: "c3", name: "Mr. Kai Yao" }] },
  { id: "CUST-009", name: "ATS Nets & Ropes Pty. Ltd.", consignee: "ATS Nets & Ropes Pty. Ltd.", country: "Australia", address: "8 Brewer Street, Clontarf QLD 4019, Australia", contactPerson: "Mr. Jason Geraghty", email: "jason@atsnetsropes.com.au", phone: "+07 3284 1199", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-010", name: "Alshark For Import & Export Co., Ltd.", consignee: "Alshark For Import & Export Co., Ltd.", country: "Egypt", address: "6 Oct. Str, Borg Elbroloss, Kafr Elshikh, Egypt", contactPerson: "Mr. Kassem Mostafa Sharshir", email: "kasimsarsid@gmail.com", phone: "+002 012 736 5955", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "FORTUNE NET & TWINE MFG. CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-011", name: "Australian Southern Exporters", consignee: "Australian Southern Exporters", country: "Australia", address: "21 Pine Freezers Rd, Port Lincoln, South Australia 5606", contactPerson: "Ms. Anne Tapley", email: "info@challengefisheries.com.au", phone: "+0061 408 837139", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-012", name: "Breakwater Fishing Products", consignee: "Breakwater Fishing Products", country: "Australia", address: "132-138 Panoramic Drive, Port Lincoln, South Australia 5606", contactPerson: "Mr. Nathan Fauser", email: "nathanandjulz@gmail.com", phone: "+61 409 451 082", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "FORTUNE NET & TWINE MFG. CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Nathan Fauser", email: "nathanandjulz@gmail.com", isPrimary: true }, { id: "c2", name: "Ms. Julie Fauser" }] },
  { id: "CUST-013", name: "Caroline Fisheries Corp., Inc.", consignee: "Caroline Fisheries Corp., Inc.", country: "Micronesia", address: "Dekehtik Port, Nett P.O. Box 7, Kolonia, Pohnpei, FM 96941", contactPerson: "Mr. Juan Carlos Munoz", email: "marko@cfctuna.com", phone: "+691 320 5791", defaultPaymentTerms: "100% TT upon confirmation of order", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Juan Carlos Munoz", email: "jcmunoz@cfctuna.com", isPrimary: true }, { id: "c2", name: "Mr. Marko Kamber", email: "marko@cfctuna.com" }] },
  { id: "CUST-014", name: "(CKS) Chye Khiang Seng (M) Sdn. Bhd.", consignee: "(CKS) Chye Khiang Seng (M) Sdn. Bhd.", country: "Malaysia", address: "Wisma C.K.S., 155 Jalan Kapar, P.O. Box 211, 41720 Klang, Selangor, Malaysia", contactPerson: "Mr. Chew Guan Ho", email: "byencks@gmail.com", phone: "+00 603 3341 3233", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Chew Guan Ho", isPrimary: true }, { id: "c2", name: "Ms. Bee Yen", email: "byencks@gmail.com" }] },
  { id: "CUST-015", name: "Casamar (Seychelles) Ltd.", consignee: "Casamar (Seychelles) Ltd.", country: "Seychelles", address: "P.O. Box 272, Victoria, Mahe, Seychelles", contactPerson: "Mr. David Fabien", email: "davejourdan6@gmail.com", phone: "+248 2710253", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-016", name: "Fitec International", consignee: "Fitec International", country: "United States", address: "3889 East Raines Rd, Memphis, TN 38118, U.S.A.", contactPerson: "Mr. Mark Hall", email: "markhall@fitecgroup.com", phone: "+00 1 901 366 9144", defaultPaymentTerms: "20% deposit, 80% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-017", name: "Grup El Remitger SL", consignee: "Grup El Remitger SL", country: "Spain", address: "Can Barneda s/n, Pol. Ind. Moli d'en Xec Nau 28, 08291 Ripollet, Barcelona, Spain", contactPerson: "Mr. Fausti Martinez", email: "fausti@elremitger.com", phone: "+00 349 3224 0000", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-018", name: "Haverford Brands Pty. Ltd.", consignee: "Haverford Brands Pty. Ltd.", country: "Australia", address: "Unit 7/1-13 Childs Road, Chipping Norton, NSW 2170, Australia", contactPerson: "Mr. Daniel Winney", email: "danielwinney@haverford.com.au", phone: "+00 612 9771 5288", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Daniel Winney", title: "Director", email: "danielwinney@haverford.com.au", isPrimary: true }, { id: "c2", name: "Mr. Mark Winney", email: "markwinney@haverford.com.au" }] },
  { id: "CUST-019", name: "I.F. (Thailand) Co. Ltd.", consignee: "I.F. (Thailand) Co. Ltd.", country: "Thailand", address: "1134/225 Prima Srinakharin Bldg. C, 1st Fl., Srinakharin Rd, Suan Luang, Bangkok 10250, Thailand", contactPerson: "Mr. Eric Laurenson", email: "eric@internetfrance-group.com", phone: "+00 662 327 6598", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Eric Laurenson", email: "eric@internetfrance-group.com", isPrimary: true }, { id: "c2", name: "Mr. Edward Laurenson", email: "edward@internetfrance-group.com" }] },
  { id: "CUST-020", name: "Internet France S.A.R.L.", consignee: "Internet France S.A.R.L.", country: "France", address: "745 Rue Du Marais, 62170 Estreelles, France", contactPerson: "Mr. Eric Laurenson", email: "eric@internetfrance-group.com", phone: "+003 03 2106 1808", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Eric Laurenson", email: "eric@internetfrance-group.com", isPrimary: true }, { id: "c2", name: "Mr. Edward Laurenson", email: "edward@internetfrance-group.com" }] },
  { id: "CUST-021", name: "Kinoshita Fishing Net Mfg. Co., Ltd.", consignee: "Kinoshita Fishing Net Mfg. Co., Ltd.", country: "Japan", address: "Harimakaito 1, Nishihazu-Cho, Nishio-Shi, Aichi 444-0703, Japan", contactPerson: "Mr. Takashi Tomokiyo", email: "tomokiyo@muketsu.co.jp", phone: "+0563 62 3111", defaultPaymentTerms: "100% TT against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Takashi Tomokiyo", email: "tomokiyo@muketsu.co.jp", isPrimary: true }, { id: "c2", name: "Mr. Mitsunori Kimura", email: "m.kimura@muketsu.co.jp" }] },
  { id: "CUST-022", name: "Mary Stores (PT Summer Jaya Bumi Lestari)", consignee: "Mary Stores (PT Summer Jaya Bumi Lestari)", country: "Sri Lanka", address: "214 Bankshall Street, Colombo 11, Sri Lanka", contactPerson: "Mr. Denny Leon", email: "denny66joe@yahoo.co.in", phone: "+00 941 1232 0913", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-023", name: "Marnikol Fisheries Pty., Ltd.", consignee: "Marnikol Fisheries Pty., Ltd.", country: "Australia", address: "PO Box 10, Port Lincoln, South Australia 5606", contactPerson: "Dr. Daryl Evans", email: "marnikol@bigpond.net.au", phone: "+08 8683 3900", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Dr. Daryl Evans", isPrimary: true }, { id: "c2", name: "Ms. Karen Scott" }] },
  { id: "CUST-024", name: "Nets Tasmania Pty. Ltd.", consignee: "Nets Tasmania Pty. Ltd.", country: "Australia", address: "172 Kermandie Road, Geeveston, Tasmania 7116, Australia", contactPerson: "Mr. Robert Bruce", email: "donsnets@bigpond.com", phone: "+00 613 6229 3348", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Robert Bruce", email: "donsnets@bigpond.com", isPrimary: true }, { id: "c2", name: "Mr. Don Latham", email: "donsnets1@bigpond.com" }, { id: "c3", name: "Mr. Steven Latham", email: "donsnets2@bigpond.com" }] },
  { id: "CUST-025", name: "OY Nerival Group AB", consignee: "OY Nerival Group AB", country: "Finland", address: "Nuotiopiha 1 A 8, FI-02600 Espoo, Finland", contactPerson: "Mr. Ilpo Tapani", email: "info@nerivalgroup.fi", phone: "+358 0 40 911 5631", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Ilpo Tapani", email: "info@nerivalgroup.fi", isPrimary: true }, { id: "c2", name: "Mr. Muni Lipsky", email: "munilipsky@yahoo.com" }] },
  { id: "CUST-026", name: "Southern Supplies", consignee: "Southern Supplies", country: "United States", address: "326 East Howard Ave., Biloxi, MS 39530, U.S.A.", contactPerson: "Mr. John Nguyen", email: "johnssc6801@yahoo.com", phone: "+001 228 435 4401", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. John Nguyen", email: "johnssc6801@yahoo.com", isPrimary: true }, { id: "c2", name: "Ms. Linda Nguyen", email: "sscjohn6801@yahoo.com" }] },
  { id: "CUST-027", name: "Sumipesca S.A.", consignee: "Sumipesca S.A.", country: "Spain", address: "Navalaldea, B2A, 20110 Pasai Donibane, Guipuzcoa, Spain", contactPerson: "Mr. Zuhaitz Gonzalez Gutierrez", email: "administracion@sumipesca.es", phone: "+00 34 943 513900", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Zuhaitz Gonzalez Gutierrez", email: "zuhaitz@sumipesca.es", isPrimary: true }, { id: "c2", name: "Ms. Eneritz Sistiaga Alcaraz" }] },
  { id: "CUST-028", name: "Trident Nets Pty Ltd.", consignee: "Trident Nets Pty Ltd.", country: "Australia", address: "25 Humphreys St, New Norfolk, Tasmania 7140, Australia", contactPerson: "Mr. Danny Farrow", email: "tridentnetsptyltd@bigpond.com", phone: "+00 613 6261 3400", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-029", name: "The Deckstore Pty Ltd.", consignee: "The Deckstore Pty Ltd.", country: "Australia", address: "39 Tingira Street, Portsmith, Cairns, Queensland 4870, Australia", contactPerson: "Ms. Theresa Lowe", email: "theresa@thedeckstore.com.au", phone: "+00 617 4035 1951", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-030", name: "Wakamatsu Trading Co., Ltd.", consignee: "Wakamatsu Trading Co., Ltd.", country: "Japan", address: "#501, 1-10, 3-Chome Hirano-machi, 541-0046 Chuoku, Osaka, Japan", contactPerson: "Mr. Shinobu Hirose", email: "hiroses@kcn.ne.jp", phone: "+81 6 6229 2151", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-031", name: "White Fisheries Enterprise", consignee: "White Fisheries Enterprise", country: "Australia", address: "Port Lincoln, South Australia 5606", contactPerson: "Mr. Paul Giblin", email: "whitefisheries1@bigpond.com", phone: "—", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Paul Giblin", email: "whitefisheries1@bigpond.com", isPrimary: true }, { id: "c2", name: "Mr. Verne Lindsay", email: "vklindsay1@bigpond.com" }] },
  { id: "CUST-032", name: "Fortune Net Group - Div. South America", consignee: "Fortune Net Group - Div. South America", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  // ---- INSUPES sub-accounts (FORTUNE NET GROUP - DIV. SOUTH AMERICA), Chile — shared agent contact ----
  { id: "CUST-033", name: "AL8 Trading Ltda.", consignee: "AL8 Trading Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-034", name: "Blumar S.A.", consignee: "Blumar S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-035", name: "Bruening S.A.", consignee: "Bruening S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-036", name: "Corpesca S.A.", consignee: "Corpesca S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-037", name: "Comercial Isla Lennox S.P.A.", consignee: "Comercial Isla Lennox S.P.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "55% deposit, 45% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-038", name: "Com. Chilean Surfish Ltda.", consignee: "Com. Chilean Surfish Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-039", name: "Columbia Trading S.A.", consignee: "Columbia Trading S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-040", name: "Euro Náutica", consignee: "Euro Náutica", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "25% deposit, 75% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-041", name: "Eric Letelier", consignee: "Eric Letelier", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-042", name: "Fimar Centro Sur S.P.A.", consignee: "Fimar Centro Sur S.P.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, balance by LC before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-043", name: "Fimar Chile Ltda.", consignee: "Fimar Chile Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "20% deposit, balance by LC before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-044", name: "Gandara Chile S.A.", consignee: "Gandara Chile S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-045", name: "Hinrichsen & Vasey Operaciones Ltda.", consignee: "Hinrichsen & Vasey Operaciones Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-046", name: "Insumos Pesqueros Ltda.", consignee: "Insumos Pesqueros Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-047", name: "Multivalores S.A.", consignee: "Multivalores S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-048", name: "Omega Seafoods Ltda.", consignee: "Omega Seafoods Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-049", name: "Prodinsa S.A.", consignee: "Prodinsa S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "20% deposit, 80% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-050", name: "Redes, Cabos e Hilos S.P.A.", consignee: "Redes, Cabos e Hilos S.P.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-051", name: "Redes Nitto Chile Ltda.", consignee: "Redes Nitto Chile Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-052", name: "Sindicato (Caleta Papudo)", consignee: "Sindicato (Caleta Papudo)", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "50% deposit, 50% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-053", name: "Soc. Pesquera Saez Y Saez Ltda.", consignee: "Soc. Pesquera Saez Y Saez Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-054", name: "Supply & Operation S.A.C.", consignee: "Supply & Operation S.A.C.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-055", name: "Terramar Pesca SPA.", consignee: "Terramar Pesca SPA.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-056", name: "Tradestar Importacao Ltda.", consignee: "Tradestar Importacao Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "25% deposit, 75% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
];

// -------------------------------------------------------------------------
// Standard Shipment / Validity phrasing pulled from the export client master
// (real terms currently written by hand on every quotation) — kept as plain
// reference lists for now; wiring them into NewQuotation as suggestions is a
// follow-up once we confirm the phrasing should replace the numeric
// leadTimeWeeks/validityDays fields or sit alongside them.
// -------------------------------------------------------------------------
export const SHIPMENT_TERM_OPTIONS: string[] = [
  "7 days from receipt of deposit",
  "15 days from receipt of deposit",
  "30 days from receipt of deposit",
  "45 days from receipt of deposit",
  "60 days from receipt of deposit",
  "75 days from receipt of deposit",
  "90 days from receipt of deposit",
  "120 days from receipt of deposit",
  "150 days from receipt of deposit",
  "165 days from receipt of deposit",
  "180 days from receipt of deposit",
  "210 days from receipt of deposit",
  "7 days from receipt of LC",
  "15 days from receipt of LC",
  "30 days from receipt of LC",
  "45 days from receipt of LC",
  "60 days from receipt of LC",
  "75 days from receipt of LC",
  "90 days from receipt of LC",
  "120 days from receipt of LC",
  "150 days from receipt of LC",
  "165 days from receipt of LC",
  "180 days from receipt of LC",
  "210 days from receipt of LC",
];

export const VALIDITY_TERM_OPTIONS: string[] = [
  "7 days, thereafter subject to our final confirmation.",
  "Please confirm by return within today.",
];

export const ITEM_MASTER: ItemMaster[] = [
  { code: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/22x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 3498.37, unitWeightKg: 241.5, givenPriceKg: 11.60, defaultLaborHours: 1.4, defaultLaborRate: 2.75, defaultWastageKg: 4.8, defaultTwineKg: 0.9, defaultTwineRate: 6.64 },
  { code: "NET-96-210-20-350", description: "No.96(210/20x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/20x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 3299.99, unitWeightKg: 227.9, givenPriceKg: 11.30, defaultLaborHours: 1.3, defaultLaborRate: 2.75, defaultWastageKg: 4.5, defaultTwineKg: 0.85, defaultTwineRate: 6.64 },
  { code: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/16x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 2387.03, unitWeightKg: 164.85, givenPriceKg: 11.00, defaultLaborHours: 1.1, defaultLaborRate: 2.75, defaultWastageKg: 3.3, defaultTwineKg: 0.7, defaultTwineRate: 6.64 },
  { code: "NET-72-210-14-350", description: "No.72(210/14x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/14x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 2080.78, unitWeightKg: 143.7, givenPriceKg: 10.80, defaultLaborHours: 1.0, defaultLaborRate: 2.75, defaultWastageKg: 2.9, defaultTwineKg: 0.6, defaultTwineRate: 6.64 },
  { code: "NET-42-250-08-8IN", description: "No.42(250/08x16) 8\" Hi-Ex Braided Net", material: "Hi-Ex", plySize: "250D/08x16", meshSize: "8\"", meshDepth: "50md x 120fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 936.33, unitWeightKg: 33.9, givenPriceKg: 14.50, defaultLaborHours: 0.6, defaultLaborRate: 2.75, defaultWastageKg: 0.7, defaultTwineKg: 0.3, defaultTwineRate: 6.64 },
  { code: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", material: "Hi-Ex", plySize: "250D/20x16", meshSize: "5\"", meshDepth: "15md x 120fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 1063.98, unitWeightKg: 38.55, givenPriceKg: 14.00, defaultLaborHours: 0.65, defaultLaborRate: 2.75, defaultWastageKg: 0.8, defaultTwineKg: 0.32, defaultTwineRate: 6.64 },
  { code: "TWINE-HEX-TARRED", description: "H-Ex Lacing Twine, Tarred", material: "Hi-Ex", plySize: "—", meshSize: "—", meshDepth: "—", color: "Tarred", uom: "KGS", unitPrice: 6.64, unitWeightKg: 1, givenPriceKg: 5.10, defaultLaborHours: 0, defaultLaborRate: 0, defaultWastageKg: 0, defaultTwineKg: 0, defaultTwineRate: 0 },
];

// -------------------------------------------------------------------------
// Pricing rule engine — lookup tables and rule chain (Part A/C of the
// discovery doc). MD/DW/Insurance rows use the simulation doc's own observed
// figures so the engine is traceable back to the original run: §5.2 recorded
// 122MD -> +0.1750, DW (50FL) -> +0.5000, and insurance at 0.66% of the
// running total. Intermediate buckets interpolate linearly from those anchors
// (MD ~0.001434/md, DW 0.01/fl). Editable from Settings -> Pricing Rules.
// -------------------------------------------------------------------------
export const LOOKUP_TABLES: LookupTable[] = [
  {
    id: "lt_md",
    name: "Mesh Depth (MD) rate",
    valueKind: "amount",
    rows: [
      { key: "122", value: 0.175 }, // observed live, doc §5.2 row 6
      { key: "50", value: 0.072 },
      { key: "15", value: 0.022 },
      { key: "default", value: 0 },
    ],
  },
  {
    id: "lt_dw",
    name: "Depth-Way (float length) rate",
    valueKind: "amount",
    rows: [
      { key: "35", value: 0.35 },
      { key: "50", value: 0.5 }, // observed live, doc §5.2 row 7
      { key: "60", value: 0.6 },
      { key: "70", value: 0.7 },
      { key: "90", value: 0.9 },
      { key: "120", value: 1.2 },
      { key: "150", value: 1.5 },
      { key: "180", value: 1.8 },
      { key: "default", value: 0 },
    ],
  },
  {
    id: "lt_ins",
    name: "Insurance rate (by category)",
    // Percent, not currency — 0.66 means 0.66% of the running price per kg.
    valueKind: "percent",
    rows: [
      { key: "net", value: 0.66 },
      { key: "twine", value: 0.18 },
      { key: "default", value: 0 },
    ],
  },
];

export const PRICING_RULES: PricingRule[] = [
  { id: "r_comm", code: "COMMISSION", label: "Commission", operation: "add", basis: "percent_of_result", rate: 3, sequence: 1, enabled: true },
  { id: "r_markup", code: "PERCENTAGE", label: "Markup", operation: "add", basis: "percent_of_base", rate: 5, sequence: 2, enabled: true },
  { id: "r_discount", code: "PERCENTAGE", label: "Discount", operation: "subtract", basis: "percent_of_base", rate: 5, sequence: 3, enabled: false },
  { id: "r_surcharge", code: "AMOUNT", label: "Flat surcharge", operation: "add", basis: "flat_amount", rate: 0.1, sequence: 4, enabled: false },
  { id: "r_deduction", code: "AMOUNT", label: "Flat deduction", operation: "subtract", basis: "flat_amount", rate: 0.2, sequence: 5, enabled: false },
  { id: "r_md", code: "MD_COMPUTATION", label: "Mesh Depth adjustment", operation: "add", basis: "lookup_table", rate: 0, lookupTableId: "lt_md", sequence: 6, enabled: true },
  { id: "r_dw", code: "DW_COMPUTATION", label: "Depth-Way adjustment", operation: "add", basis: "lookup_table", rate: 0, lookupTableId: "lt_dw", sequence: 7, enabled: true },
  { id: "r_ins", code: "INSURANCE", label: "Insurance", operation: "add", basis: "lookup_table", rate: 0, lookupTableId: "lt_ins", sequence: 8, enabled: true },
];

// -------------------------------------------------------------------------
// Helper to build a lifecycle stage array up to a given current stage.
// -------------------------------------------------------------------------
function buildStages(
  currentStage: OrderStage,
  overrides: Partial<Record<OrderStage, Partial<StageRecord>>> = {}
): StageRecord[] {
  const currentIdx = ORDER_STAGES.findIndex((s) => s.id === currentStage);
  return ORDER_STAGES.map((s, idx) => {
    let status: StageRecord["status"] = "pending";
    if (idx < currentIdx) status = "completed";
    else if (idx === currentIdx) status = "in_progress";
    const base: StageRecord = {
      stage: s.id,
      status,
      responsibleRole: s.role,
    };
    return { ...base, ...(overrides[s.id] || {}) };
  });
}

// -------------------------------------------------------------------------
// Quotations
// -------------------------------------------------------------------------
export const QUOTATIONS: Quotation[] = [
  {
    id: "PI-33002",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-05-02", changedBy: "Grace Tan", note: "Initial issue" }],
    customerId: "CUST-006",
    consignee: "West Coast Marine Supply Inc.",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-05-02",
    paymentTerms: "50% DP, 50% before loading",
    moq: "2 pcs per spec",
    leadTimeWeeks: 6,
    estimatedShipmentDate: "2026-07-14",
    items: [
      { id: "L1", itemCode: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 4, unit: "PCS", unitPrice: 3498.37, weightKg: 966, totalPrice: 13993.48 },
      { id: "L2", itemCode: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 6, unit: "PCS", unitPrice: 2387.03, weightKg: 989.1, totalPrice: 14322.18 },
    ],
    freight: 0,
    discount: 0,
    tax: 0,
    depositPercent: 50,
    assignedSalesperson: "Grace Tan",
    salesOrderId: "SO-1041",
    remarks: "FOB Manila. Standard export packing.",
    approver: "Marcus Reyes",
    approvedDate: "2026-05-03",
  },
  {
    id: "PI-33005",
    revisionNo: 1,
    revisions: [
      { revisionNo: 0, date: "2026-05-20", changedBy: "Grace Tan", note: "Initial issue" },
      { revisionNo: 1, date: "2026-05-24", changedBy: "Grace Tan", note: "Adjusted mesh depth per factory counter-offer" },
    ],
    customerId: "CUST-003",
    consignee: "PT Samudra Jaring Nusantara",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-05-24",
    paymentTerms: "30% DP, 70% before loading",
    moq: "3 pcs per spec",
    leadTimeWeeks: 7,
    estimatedShipmentDate: "2026-07-30",
    items: [
      { id: "L1", itemCode: "NET-72-210-14-350", description: "No.72(210/14x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 5, unit: "PCS", unitPrice: 2080.78, weightKg: 1437, totalPrice: 10403.90 },
      { id: "L3", itemCode: "NET-42-250-08-8IN", description: "No.42(250/08x16) 8\" Hi-Ex Braided Net", specification: "50md x 120fl (1066ml)", qtyPcs: 12, unit: "PCS", unitPrice: 936.33, weightKg: 406.8, totalPrice: 11235.96 },
    ],
    freight: 850,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    salesOrderId: "SO-1044",
    remarks: "FOB Manila.",
    approver: "Grace Tan",
    approvedDate: "2026-05-25",
  },
  {
    id: "PI-33009",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-06-18", changedBy: "Marcus Reyes", note: "Initial issue" }],
    customerId: "CUST-002",
    consignee: "Nordfisk Trading AS",
    status: "sent",
    currency: "USD",
    validityDays: 10,
    issueDate: "2026-06-18",
    paymentTerms: "30% DP, 70% before loading",
    moq: "2 pcs per spec",
    leadTimeWeeks: 6,
    estimatedShipmentDate: "2026-08-20",
    items: [
      { id: "L1", itemCode: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", specification: "15md x 120fl", qtyPcs: 8, unit: "PCS", unitPrice: 1063.98, weightKg: 308.4, totalPrice: 8511.84 },
    ],
    freight: 420,
    discount: 150,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    remarks: "Awaiting customer response. Follow-up scheduled.",
  },
  {
    id: "PI-33011",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-07-08", changedBy: "Grace Tan", note: "Initial issue" }],
    customerId: "CUST-004",
    consignee: "Golden Reef Fisheries Ltd.",
    status: "for_approval",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-07-08",
    paymentTerms: "40% DP, 60% before loading",
    moq: "3 pcs per spec",
    leadTimeWeeks: 8,
    estimatedShipmentDate: "2026-09-10",
    items: [
      { id: "L1", itemCode: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", specification: "122md x 40fl (946ml)", qtyPcs: 6, unit: "PCS", unitPrice: 2387.03, weightKg: 989.1, totalPrice: 14322.18 },
      { id: "L2", itemCode: "TWINE-HEX-TARRED", description: "H-Ex Lacing Twine, Tarred", specification: "Tarred, 6mm", qtyPcs: 320, unit: "KGS", unitPrice: 6.64, weightKg: 320, totalPrice: 2124.80 },
    ],
    freight: 0,
    discount: 0,
    tax: 0,
    depositPercent: 40,
    assignedSalesperson: "Grace Tan",
    remarks: "Pending Sales Manager approval — first order for this customer, credit terms to confirm.",
  },
  {
    id: "PI-33012",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-07-22", changedBy: "Marcus Reyes", note: "Initial issue, per Fortune Net & Twine reference PI #33007" }],
    customerId: "CUST-001",
    consignee: "KTI Company Limited",
    status: "draft",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-07-22",
    paymentTerms: "20% deposit, 80% before shipment",
    moq: "1 pc per spec",
    leadTimeWeeks: 8,
    estimatedShipmentDate: "2026-11-19",
    items: [
      { id: "L1", itemCode: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 2, unit: "PCS", unitPrice: 3498.37, weightKg: 483, totalPrice: 6996.74 },
      { id: "L2", itemCode: "NET-96-210-20-350", description: "No.96(210/20x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 2, unit: "PCS", unitPrice: 3299.99, weightKg: 455.8, totalPrice: 6599.98 },
      { id: "L3", itemCode: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 3, unit: "PCS", unitPrice: 2387.03, weightKg: 989.1, totalPrice: 7161.09 },
    ],
    freight: 0,
    discount: 0,
    tax: 0,
    depositPercent: 20,
    assignedSalesperson: "Marcus Reyes",
    remarks: "Reur email inquiry dated July 16, 2026. NPD 2612. Not yet submitted.",
  },
  {
    id: "PI-32994",
    revisionNo: 2,
    revisions: [
      { revisionNo: 0, date: "2026-04-02", changedBy: "Grace Tan", note: "Initial issue" },
      { revisionNo: 1, date: "2026-04-09", changedBy: "Grace Tan", note: "Quantity revised down per customer request" },
      { revisionNo: 2, date: "2026-04-15", changedBy: "Grace Tan", note: "Final pricing locked after negotiation" },
    ],
    customerId: "CUST-005",
    consignee: "Pacífico Redes S.A. de C.V.",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-04-15",
    paymentTerms: "30% DP, 70% before loading",
    moq: "2 pcs per spec",
    leadTimeWeeks: 5,
    estimatedShipmentDate: "2026-06-02",
    items: [
      { id: "L1", itemCode: "NET-72-210-14-350", description: "No.72(210/14x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 3, unit: "PCS", unitPrice: 2080.78, weightKg: 862.2, totalPrice: 6242.34 },
    ],
    freight: 300,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Grace Tan",
    salesOrderId: "SO-1039",
    remarks: "Completed order — reference for repeat business.",
    approver: "Marcus Reyes",
    approvedDate: "2026-04-16",
  },
  {
    id: "PI-33007-R1",
    revisionNo: 1,
    revisions: [
      { revisionNo: 0, date: "2026-06-30", changedBy: "Marcus Reyes", note: "Initial issue" },
      { revisionNo: 1, date: "2026-07-09", changedBy: "Marcus Reyes", note: "Customer requested minimum quantity clause on #210(42x16), 5\" selvage" },
    ],
    customerId: "CUST-007",
    consignee: "Senegal Peche Atlantique",
    status: "under_negotiation",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-07-09",
    paymentTerms: "30% DP, 70% before loading",
    moq: "1 pc minimum on selvage items",
    leadTimeWeeks: 9,
    estimatedShipmentDate: "2026-09-25",
    items: [
      { id: "L1", itemCode: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", specification: "15md x 120fl", qtyPcs: 4, unit: "PCS", unitPrice: 1063.98, weightKg: 154.2, totalPrice: 4255.92 },
    ],
    freight: 610,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    remarks: "Customer negotiating selvage length minimums to avoid short-length joins.",
    customerResponseNote: "Customer requests standard selvage length be guaranteed in writing before acceptance.",
  },
];

// -------------------------------------------------------------------------
// Sales Orders — covering the required demo scenarios
// -------------------------------------------------------------------------
export const SALES_ORDERS: SalesOrder[] = [
  // Raised straight from INQ-2044 on the customer's own PO. No quotation exists behind it, which
  // is the case the Customer Inquiries module was built to show: the PO is the agreement, so the
  // order skips Customer Confirmation and starts at Internal Verification.
  {
    id: "SO-2044",
    inquiryId: "INQ-2044",
    customerPoNo: "PO-88214",
    customerId: "CUST-002",
    consignee: "KTI Company Limited",
    country: "South Korea",
    currency: "USD",
    orderValue: 18400,
    orderDate: "2026-08-05",
    requestedDeliveryDate: "2026-10-15",
    currentStage: "deposit",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "not_started",
    productionQtyOrdered: 0,
    productionQtyCompleted: 0,
    productionQtyRejected: 0,
    stages: buildStages("deposit", {
      deposit: { pendingAction: "Awaiting 30% deposit against PO-88214" },
    }),
  },
  {
    id: "SO-1041",
    quotationId: "PI-33002",
    customerId: "CUST-006",
    consignee: "West Coast Marine Supply Inc.",
    country: "United States",
    currency: "USD",
    orderValue: 28315.66,
    orderDate: "2026-05-04",
    requestedDeliveryDate: "2026-07-14",
    currentStage: "completed",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "completed",
    productionQtyOrdered: 10,
    productionQtyCompleted: 10,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-06-20",
    actualCompletionDate: "2026-06-18",
    invoiceId: "CI-9041",
    stages: buildStages("completed", {
      quotation: { status: "completed", completedDate: "2026-05-03" },
      customer_confirmation: { status: "completed", completedDate: "2026-05-04" },
      deposit: { status: "completed", completedDate: "2026-05-08" },
      production: { status: "completed", completedDate: "2026-06-18" },
      packing: { status: "completed", completedDate: "2026-06-25" },
      inspection: { status: "completed", completedDate: "2026-06-28" },
      shipment: { status: "completed", completedDate: "2026-07-14" },
      final_payment: { status: "completed", completedDate: "2026-07-10" },
      documents: { status: "completed", completedDate: "2026-07-15" },
      completed: { status: "completed", completedDate: "2026-07-15" },
    }),
  },
  {
    id: "SO-1044",
    quotationId: "PI-33005",
    customerId: "CUST-003",
    consignee: "PT Samudra Jaring Nusantara",
    country: "Indonesia",
    currency: "USD",
    orderValue: 21639.86,
    orderDate: "2026-05-26",
    requestedDeliveryDate: "2026-07-30",
    currentStage: "shipment",
    priority: "high",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "completed",
    productionQtyOrdered: 17,
    productionQtyCompleted: 17,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-07-10",
    actualCompletionDate: "2026-07-09",
    stages: buildStages("shipment", {
      quotation: { status: "completed", completedDate: "2026-05-25" },
      customer_confirmation: { status: "completed", completedDate: "2026-05-26" },
      deposit: { status: "completed", completedDate: "2026-05-30" },
      production: { status: "completed", completedDate: "2026-07-09" },
      packing: { status: "completed", completedDate: "2026-07-16" },
      inspection: { status: "completed", completedDate: "2026-07-19" },
      shipment: {
        status: "blocked",
        responsibleRole: "Logistics",
        pendingAction: "Remaining balance must clear before container loading",
        blocker: "Remaining balance (70%) not yet verified by Finance",
      },
    }),
  },
  {
    id: "SO-1039",
    quotationId: "PI-32994",
    customerId: "CUST-005",
    consignee: "Pacífico Redes S.A. de C.V.",
    country: "Mexico",
    currency: "USD",
    orderValue: 6542.34,
    orderDate: "2026-04-17",
    requestedDeliveryDate: "2026-06-02",
    currentStage: "completed",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "completed",
    productionQtyOrdered: 3,
    productionQtyCompleted: 3,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-05-20",
    actualCompletionDate: "2026-05-19",
    invoiceId: "CI-9039",
    stages: buildStages("completed", {
      quotation: { status: "completed", completedDate: "2026-04-16" },
      customer_confirmation: { status: "completed", completedDate: "2026-04-17" },
      deposit: { status: "completed", completedDate: "2026-04-21" },
      production: { status: "completed", completedDate: "2026-05-19" },
      packing: { status: "completed", completedDate: "2026-05-24" },
      inspection: { status: "completed", completedDate: "2026-05-26" },
      shipment: { status: "completed", completedDate: "2026-06-02" },
      final_payment: { status: "completed", completedDate: "2026-05-30" },
      documents: { status: "completed", completedDate: "2026-06-03" },
      completed: { status: "completed", completedDate: "2026-06-03" },
    }),
  },
  {
    id: "SO-1046",
    quotationId: "PI-33011",
    customerId: "CUST-004",
    consignee: "Golden Reef Fisheries Ltd.",
    country: "Bangladesh",
    currency: "USD",
    orderValue: 16446.98,
    orderDate: "2026-07-10",
    requestedDeliveryDate: "2026-09-10",
    currentStage: "deposit",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "not_started",
    productionQtyOrdered: 6,
    productionQtyCompleted: 0,
    productionQtyRejected: 0,
    stages: buildStages("deposit", {
      quotation: { status: "completed", completedDate: "2026-07-08" },
      customer_confirmation: { status: "completed", completedDate: "2026-07-10" },
      deposit: {
        status: "in_progress",
        responsibleRole: "Finance",
        pendingAction: "Verify 40% deposit against submitted remittance copy",
      },
    }),
  },
  {
    id: "SO-1047",
    quotationId: "PI-33005",
    customerId: "CUST-003",
    consignee: "PT Samudra Jaring Nusantara — repeat order",
    country: "Indonesia",
    currency: "USD",
    orderValue: 34120.5,
    orderDate: "2026-07-02",
    requestedDeliveryDate: "2026-09-01",
    currentStage: "packing",
    priority: "high",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "in_production",
    productionQtyOrdered: 24,
    productionQtyCompleted: 14,
    productionQtyRejected: 1,
    plannedCompletionDate: "2026-08-10",
    stages: buildStages("packing", {
      quotation: { status: "completed", completedDate: "2026-06-28" },
      customer_confirmation: { status: "completed", completedDate: "2026-07-01" },
      deposit: { status: "completed", completedDate: "2026-07-05" },
      packing: {
        status: "in_progress",
        responsibleRole: "Logistics",
        pendingAction: "Raise the packing list — 14 of 24 pcs off the line so far",
      },
    }),
  },
  {
    id: "SO-1048",
    quotationId: "PI-33009",
    customerId: "CUST-002",
    consignee: "Nordfisk Trading AS",
    country: "Norway",
    currency: "USD",
    orderValue: 25400,
    orderDate: "2026-07-15",
    requestedDeliveryDate: "2026-09-30",
    currentStage: "packing",
    priority: "urgent",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "on_hold",
    productionQtyOrdered: 8,
    productionQtyCompleted: 2,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-08-05",
    delayReason: "Awaiting raw material restock for Hi-Ex 250D twine",
    stages: buildStages("packing", {
      quotation: { status: "completed", completedDate: "2026-07-12" },
      customer_confirmation: { status: "completed", completedDate: "2026-07-14" },
      deposit: { status: "completed", completedDate: "2026-07-17" },
      packing: {
        status: "blocked",
        responsibleRole: "Logistics",
        pendingAction: "Raise the packing list once the raw material restock is confirmed",
        blocker: "Delayed 2 days — raw material shortage on Hi-Ex 250D twine",
      },
    }),
  },
  {
    id: "SO-1050",
    quotationId: "PI-33002",
    customerId: "CUST-006",
    consignee: "West Coast Marine Supply Inc. — Order 2",
    country: "United States",
    currency: "USD",
    orderValue: 19870,
    orderDate: "2026-07-20",
    requestedDeliveryDate: "2026-09-18",
    currentStage: "packing",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "completed",
    productionQtyOrdered: 9,
    productionQtyCompleted: 9,
    productionQtyRejected: 0,
    actualCompletionDate: "2026-07-28",
    stages: buildStages("packing", {
      quotation: { status: "completed", completedDate: "2026-07-18" },
      customer_confirmation: { status: "completed", completedDate: "2026-07-20" },
      deposit: { status: "completed", completedDate: "2026-07-23" },
      production: { status: "completed", completedDate: "2026-07-28" },
      packing: {
        status: "in_progress",
        responsibleRole: "Logistics",
        pendingAction: "Awaiting customer confirmation of Tentative Packing List",
      },
    }),
  },
  {
    id: "SO-1051",
    quotationId: "PI-33005",
    customerId: "CUST-007",
    consignee: "Senegal Peche Atlantique",
    country: "Senegal",
    currency: "USD",
    orderValue: 4255.92,
    orderDate: "2026-07-26",
    requestedDeliveryDate: "2026-09-25",
    currentStage: "customer_confirmation",
    priority: "standard",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "not_started",
    productionQtyOrdered: 4,
    productionQtyCompleted: 0,
    productionQtyRejected: 0,
    stages: buildStages("customer_confirmation", {
      quotation: { status: "completed", completedDate: "2026-07-24" },
      customer_confirmation: {
        status: "in_progress",
        responsibleRole: "Sales",
        pendingAction: "Awaiting signed PO from customer",
      },
    }),
  },
];

// -------------------------------------------------------------------------
// Payments
// -------------------------------------------------------------------------
export const PAYMENTS: PaymentRecord[] = [
  { id: "PMT-5001", salesOrderId: "SO-1041", type: "deposit", expectedAmount: 14157.83, amountReceived: 14157.83, dateReceived: "2026-05-08", bankRef: "TT-KEB-88213", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-05-08", status: "verified" },
  { id: "PMT-5002", salesOrderId: "SO-1041", type: "balance", expectedAmount: 14157.83, amountReceived: 14157.83, dateReceived: "2026-07-10", bankRef: "TT-KEB-88940", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-07-10", status: "verified" },

  { id: "PMT-5003", salesOrderId: "SO-1044", type: "deposit", expectedAmount: 6491.96, amountReceived: 6491.96, dateReceived: "2026-05-30", bankRef: "TT-BCA-44120", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-05-30", status: "verified" },
  { id: "PMT-5004", salesOrderId: "SO-1044", type: "balance", expectedAmount: 15147.90, amountReceived: 0, status: "submitted_for_verification", dueDate: "2026-07-28", remarks: "Remittance copy uploaded by customer, awaiting bank confirmation." },

  { id: "PMT-5005", salesOrderId: "SO-1039", type: "deposit", expectedAmount: 1962.70, amountReceived: 1962.70, dateReceived: "2026-04-21", bankRef: "TT-SANT-11029", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-04-21", status: "verified" },
  { id: "PMT-5006", salesOrderId: "SO-1039", type: "balance", expectedAmount: 4579.64, amountReceived: 4579.64, dateReceived: "2026-05-30", bankRef: "TT-SANT-11190", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-05-30", status: "verified" },

  { id: "PMT-5007", salesOrderId: "SO-1046", type: "deposit", expectedAmount: 6578.79, amountReceived: 6578.79, dateReceived: "2026-07-24", bankRef: "TT-SCB-30021", method: "Wire Transfer", remittanceAttached: true, status: "submitted_for_verification", remarks: "First-time customer — Finance verification pending against bank statement." },
  { id: "PMT-5008", salesOrderId: "SO-1046", type: "balance", expectedAmount: 9868.19, amountReceived: 0, status: "expected", dueDate: "2026-08-25" },

  { id: "PMT-5009", salesOrderId: "SO-1047", type: "deposit", expectedAmount: 10236.15, amountReceived: 10236.15, dateReceived: "2026-07-05", bankRef: "TT-BCA-44550", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-07-06", status: "verified" },
  { id: "PMT-5010", salesOrderId: "SO-1047", type: "balance", expectedAmount: 23884.35, amountReceived: 0, status: "expected", dueDate: "2026-08-30" },

  { id: "PMT-5011", salesOrderId: "SO-1048", type: "deposit", expectedAmount: 7620, amountReceived: 7620, dateReceived: "2026-07-17", bankRef: "TT-DNB-90144", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-07-18", status: "verified" },
  { id: "PMT-5012", salesOrderId: "SO-1048", type: "balance", expectedAmount: 17780, amountReceived: 0, status: "overdue", dueDate: "2026-07-20", remarks: "Balance now overdue — hold discussed with Sales Manager." },

  { id: "PMT-5013", salesOrderId: "SO-1050", type: "deposit", expectedAmount: 9935, amountReceived: 9935, dateReceived: "2026-07-23", bankRef: "TT-CITI-77320", method: "Wire Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-07-23", status: "verified" },
  { id: "PMT-5014", salesOrderId: "SO-1050", type: "balance", expectedAmount: 9935, amountReceived: 3000, status: "partially_paid", dueDate: "2026-08-15", remarks: "Partial remittance received; balance short by $6,935.00." },

  { id: "PMT-5015", salesOrderId: "SO-1051", type: "deposit", expectedAmount: 1276.78, amountReceived: 0, status: "expected", dueDate: "2026-08-05" },
];

// -------------------------------------------------------------------------
// Commercial Invoices
// -------------------------------------------------------------------------
export const INVOICES: CommercialInvoice[] = [
  {
    id: "CI-9041",
    salesOrderId: "SO-1041",
    quotationId: "PI-33002",
    customerId: "CUST-006",
    issueDate: "2026-07-12",
    currency: "USD",
    items: QUOTATIONS.find((q) => q.id === "PI-33002")!.items,
    freight: 0,
    discount: 0,
    tax: 0,
    status: "paid",
    shippedWeightKg: 1955.1,
    billOfLadingNo: "MAEU-8821034",
    containerNo: "MSKU-4471820",
  },
  {
    id: "CI-9039",
    salesOrderId: "SO-1039",
    quotationId: "PI-32994",
    customerId: "CUST-005",
    issueDate: "2026-05-28",
    currency: "USD",
    items: QUOTATIONS.find((q) => q.id === "PI-32994")!.items,
    freight: 300,
    discount: 0,
    tax: 0,
    status: "paid",
    shippedWeightKg: 862.2,
    billOfLadingNo: "COSU-6620981",
    containerNo: "TCLU-2093841",
  },
];

// -------------------------------------------------------------------------
// Documents
// -------------------------------------------------------------------------
export const DOCUMENTS: DocRecord[] = [
  { id: "DOC-001", name: "PI-33002 Rev.0", type: "Proforma Invoice", relatedOrderId: "SO-1041", version: 1, uploadedBy: "Grace Tan", uploadDate: "2026-05-02", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-002", name: "PO-WCM-2205", type: "Purchase Order", relatedOrderId: "SO-1041", version: 1, uploadedBy: "Grace Tan", uploadDate: "2026-05-04", approvalStatus: "n/a", isCurrent: true },
  { id: "DOC-003", name: "CI-9041", type: "Commercial Invoice", relatedOrderId: "SO-1041", version: 1, uploadedBy: "Lourdes Ibarra", uploadDate: "2026-07-12", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-004", name: "PI-33005 Rev.0", type: "Proforma Invoice", relatedOrderId: "SO-1044", version: 1, uploadedBy: "Marcus Reyes", uploadDate: "2026-05-20", approvalStatus: "approved", isCurrent: false },
  { id: "DOC-005", name: "PI-33005 Rev.1", type: "Proforma Invoice", relatedOrderId: "SO-1044", version: 2, uploadedBy: "Marcus Reyes", uploadDate: "2026-05-24", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-006", name: "Tentative Packing List — SO-1044", type: "Packing List", relatedOrderId: "SO-1044", version: 1, uploadedBy: "Ronaldo Cruz", uploadDate: "2026-07-16", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-007", name: "Remittance Copy — Deposit SO-1046", type: "Remittance Copy", relatedOrderId: "SO-1046", version: 1, uploadedBy: "Golden Reef Fisheries Ltd.", uploadDate: "2026-07-24", approvalStatus: "pending", isCurrent: true },
  { id: "DOC-008", name: "Net Plan — Golden Reef 07-08-26", type: "Net Plan", relatedOrderId: "SO-1046", version: 1, uploadedBy: "Golden Reef Fisheries Ltd.", uploadDate: "2026-07-05", approvalStatus: "n/a", isCurrent: true },
  { id: "DOC-009", name: "Customer Confirmation Email — SO-1050 PL", type: "Customer Confirmation", relatedOrderId: "SO-1050", version: 1, uploadedBy: "West Coast Marine Supply Inc.", uploadDate: "2026-07-29", approvalStatus: "pending", isCurrent: true },
  { id: "DOC-010", name: "PI-33012 Draft", type: "Proforma Invoice", relatedOrderId: undefined, version: 1, uploadedBy: "Marcus Reyes", uploadDate: "2026-07-22", approvalStatus: "pending", isCurrent: true },
];

// -------------------------------------------------------------------------
// Approvals
// -------------------------------------------------------------------------
export const APPROVALS: ApprovalRequest[] = [
  {
    id: "APR-001",
    type: "PI Approval",
    referenceId: "PI-33011",
    customerId: "CUST-004",
    requestedBy: "Grace Tan",
    requestedDate: "2026-07-08",
    dueDate: "2026-07-31",
    level: "L2 Manager",
    status: "pending",
    reason: "New customer, first order — credit terms need Sales Manager sign-off.",
  },
  {
    id: "APR-002",
    type: "Payment Clearance",
    referenceId: "SO-1046",
    customerId: "CUST-004",
    requestedBy: "Lourdes Ibarra",
    requestedDate: "2026-07-24",
    dueDate: "2026-07-31",
    level: "L1 Supervisor",
    status: "pending",
    reason: "Verify 40% deposit remittance before releasing production.",
  },
  {
    id: "APR-003",
    type: "Loading Authorization",
    referenceId: "SO-1044",
    customerId: "CUST-003",
    requestedBy: "Ronaldo Cruz",
    requestedDate: "2026-07-27",
    dueDate: "2026-07-30",
    level: "L2 Manager",
    status: "pending",
    reason: "Container ready — blocked pending remaining balance verification.",
  },
  {
    id: "APR-004",
    type: "Discount Approval",
    referenceId: "PI-33009",
    customerId: "CUST-002",
    requestedBy: "Marcus Reyes",
    requestedDate: "2026-06-18",
    dueDate: "2026-07-02",
    level: "L2 Manager",
    status: "approved",
    reason: "$150 goodwill discount for repeat customer volume commitment.",
  },
  {
    id: "APR-005",
    type: "Sales Order Verification",
    referenceId: "SO-1048",
    customerId: "CUST-002",
    requestedBy: "Marcus Reyes",
    requestedDate: "2026-07-14",
    dueDate: "2026-07-16",
    level: "L1 Supervisor",
    status: "approved",
    reason: "Customer PO matched against production capability confirmation.",
  },
];

// -------------------------------------------------------------------------
// Activity log
// -------------------------------------------------------------------------
export const ACTIVITY: ActivityEntry[] = [
  { id: "ACT-001", timestamp: "2026-07-29T09:14:00+08:00", user: "West Coast Marine Supply Inc.", department: "Customer", action: "Uploaded packing list confirmation email", recordType: "Sales Order", recordId: "SO-1050", comment: "Customer confirmed quantities, requested container photo before loading." },
  { id: "ACT-002", timestamp: "2026-07-28T16:02:00+08:00", user: "Ronaldo Cruz", department: "Logistics", action: "Production completion recorded", previousStatus: "In Production", newStatus: "Completed", recordType: "Production Order", recordId: "SO-1050" },
  { id: "ACT-003", timestamp: "2026-07-27T11:40:00+08:00", user: "Ronaldo Cruz", department: "Logistics", action: "Requested loading authorization", recordType: "Sales Order", recordId: "SO-1044", comment: "Container packed, awaiting Finance clearance on remaining balance." },
  { id: "ACT-004", timestamp: "2026-07-26T08:55:00+08:00", user: "Marcus Reyes", department: "Sales", action: "Sales order created from accepted PI", previousStatus: "Quotation Accepted", newStatus: "Customer Confirmation", recordType: "Sales Order", recordId: "SO-1051" },
  { id: "ACT-005", timestamp: "2026-07-24T14:20:00+08:00", user: "Golden Reef Fisheries Ltd.", department: "Customer", action: "Remittance copy submitted for deposit", recordType: "Payment", recordId: "PMT-5007", comment: "40% deposit, TT reference TT-SCB-30021." },
  { id: "ACT-006", timestamp: "2026-07-22T10:05:00+08:00", user: "Marcus Reyes", department: "Sales", action: "Drafted new Proforma Invoice", recordType: "Quotation", recordId: "PI-33012" },
  { id: "ACT-007", timestamp: "2026-07-20T09:30:00+08:00", user: "Lourdes Ibarra", department: "Finance", action: "Verified deposit payment", previousStatus: "Submitted for Verification", newStatus: "Verified", recordType: "Payment", recordId: "PMT-5013" },
  { id: "ACT-008", timestamp: "2026-07-19T13:00:00+08:00", user: "System", department: "System", action: "Production delayed — raw material shortage flagged", previousStatus: "In Production", newStatus: "On Hold", recordType: "Sales Order", recordId: "SO-1048" },
  { id: "ACT-009", timestamp: "2026-07-16T15:44:00+08:00", user: "Ronaldo Cruz", department: "Logistics", action: "Tentative packing list submitted for internal review", recordType: "Sales Order", recordId: "SO-1044" },
  { id: "ACT-010", timestamp: "2026-07-09T09:12:00+08:00", user: "Marcus Reyes", department: "Sales", action: "PI Revision 1 issued", previousStatus: "Rev. 0", newStatus: "Rev. 1", recordType: "Quotation", recordId: "PI-33007-R1", comment: "Selvage length minimums under negotiation." },
  { id: "ACT-011", timestamp: "2026-07-08T11:02:00+08:00", user: "Grace Tan", department: "Sales", action: "Submitted PI for Sales Manager approval", previousStatus: "Draft", newStatus: "For Approval", recordType: "Quotation", recordId: "PI-33011" },
  { id: "ACT-012", timestamp: "2026-07-06T09:00:00+08:00", user: "Lourdes Ibarra", department: "Finance", action: "Verified deposit payment", previousStatus: "Submitted for Verification", newStatus: "Verified", recordType: "Payment", recordId: "PMT-5009" },
];

export const CURRENT_USER_BY_ROLE: Record<string, string> = {
  sales_rep: "Marcus Reyes",
  sales_manager: "Grace Tan",
  factory_technical: "Edwin Santos",
  finance: "Lourdes Ibarra",
  logistics: "Ronaldo Cruz",
  management: "Ma. Teresa Villanueva",
  admin: "System Administrator",
};
