import type {
  RoleInfo,
  Customer,
  ItemMaster,
  LookupTable,
  PricingRule,
  Quotation,
  SalesOrder,
  PaymentRecord,
  CommercialInvoice,
  DocRecord,
  ApprovalRequest,
  ActivityEntry,
  StageRecord,
  OrderStage,
} from "./types";
import { ORDER_STAGES } from "./types";

export const ROLES: RoleInfo[] = [
  {
    id: "sales_rep",
    label: "Sales Representative",
    department: "Sales",
    description: "Handles inquiries, quotations, and customer follow-up.",
  },
  {
    id: "sales_manager",
    label: "Sales Manager",
    department: "Sales",
    description: "Approves quotations, discounts, and order verification.",
  },
  {
    id: "factory_technical",
    label: "Factory Technical Team",
    department: "Technical",
    description: "Assesses feasibility and confirms production specs.",
  },
  {
    id: "finance",
    label: "Finance / Accounting",
    department: "Finance",
    description: "Verifies deposits, balances, and releases financial clearance.",
  },
  {
    id: "logistics",
    label: "Exportation / Logistics",
    department: "Logistics",
    description: "Books shipments and manages loading documentation.",
  },
  {
    id: "management",
    label: "Management",
    department: "Executive",
    description: "Oversight across the full order lifecycle.",
  },
  {
    id: "admin",
    label: "System Administrator",
    department: "Admin",
    description: "Full visibility for demonstration purposes.",
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: "CUST-001",
    name: "KTI Company Limited",
    consignee: "KTI Company Limited",
    country: "South Korea",
    address: "1503-8 Dadae-dong 49486, Saha-gu, Busan, Korea",
    contactPerson: "Mr. James Jang",
    email: "james.jang@kti-trading.kr",
    phone: "+82 51 220 4471",
    defaultPaymentTerms: "20% deposit, 80% before shipment",
    defaultCurrency: "USD",
    totalOrders: 14,
    totalValueUSD: 1284300,
    outstandingBalanceUSD: 146940.26,
    since: "2019-03-11",
  },
  {
    id: "CUST-002",
    name: "Nordfisk Trading AS",
    consignee: "Nordfisk Trading AS",
    country: "Norway",
    address: "Skolegata 14, 6003 Ålesund, Norway",
    contactPerson: "Ms. Ingrid Solberg",
    email: "ingrid.solberg@nordfisk.no",
    phone: "+47 70 12 55 40",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 6,
    totalValueUSD: 402100,
    outstandingBalanceUSD: 0,
    since: "2021-06-02",
  },
  {
    id: "CUST-003",
    name: "PT Samudra Jaring Nusantara",
    consignee: "PT Samudra Jaring Nusantara",
    country: "Indonesia",
    address: "Jl. Perikanan No. 22, Muara Baru, Jakarta Utara",
    contactPerson: "Mr. Budi Hartono",
    email: "budi.hartono@samudrajaring.co.id",
    phone: "+62 21 6660 8812",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 9,
    totalValueUSD: 587250,
    outstandingBalanceUSD: 58210.4,
    since: "2020-01-19",
  },
  {
    id: "CUST-004",
    name: "Golden Reef Fisheries Ltd.",
    consignee: "Golden Reef Fisheries Ltd. / c/o Chittagong Freight Fwd.",
    country: "Bangladesh",
    address: "Agrabad Commercial Area, Chittagong 4100",
    contactPerson: "Mr. Rafiq Ahmed",
    email: "rafiq@goldenreef.com.bd",
    phone: "+880 31 251 4402",
    defaultPaymentTerms: "40% DP, 60% before loading",
    defaultCurrency: "USD",
    totalOrders: 4,
    totalValueUSD: 198400,
    outstandingBalanceUSD: 71460,
    since: "2023-02-14",
  },
  {
    id: "CUST-005",
    name: "Pacífico Redes S.A. de C.V.",
    consignee: "Pacífico Redes S.A. de C.V.",
    country: "Mexico",
    address: "Blvd. Marina Sur 341, Mazatlán, Sinaloa",
    contactPerson: "Sr. Alejandro Ruiz",
    email: "aruiz@pacificoredes.mx",
    phone: "+52 669 981 2230",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 3,
    totalValueUSD: 121600,
    outstandingBalanceUSD: 0,
    since: "2024-05-08",
  },
  {
    id: "CUST-006",
    name: "West Coast Marine Supply Inc.",
    consignee: "West Coast Marine Supply Inc.",
    country: "United States",
    address: "1180 Fisherman's Wharf Rd, San Pedro, CA 90731",
    contactPerson: "Mr. Daniel Cruz",
    email: "dcruz@wcmarinesupply.com",
    phone: "+1 310 555 0148",
    defaultPaymentTerms: "50% DP, 50% before loading",
    defaultCurrency: "USD",
    totalOrders: 11,
    totalValueUSD: 843900,
    outstandingBalanceUSD: 22150,
    since: "2018-09-27",
  },
  {
    id: "CUST-007",
    name: "Senegal Peche Atlantique",
    consignee: "Senegal Peche Atlantique",
    country: "Senegal",
    address: "Route de la Corniche, Dakar",
    contactPerson: "M. Ousmane Diallo",
    email: "o.diallo@pecheatlantique.sn",
    phone: "+221 33 842 1190",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 2,
    totalValueUSD: 76800,
    outstandingBalanceUSD: 53760,
    since: "2025-01-30",
  },
];

export const ITEM_MASTER: ItemMaster[] = [
  { code: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/22x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 3498.37, unitWeightKg: 241.5, givenPriceKg: 11.60, defaultLaborHours: 1.4, defaultLaborRate: 2.75, defaultWastageKg: 4.8, defaultTwineKg: 0.9, defaultTwineRate: 6.64 },
  { code: "NET-96-210-20-350", description: "No.96(210/20x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/20x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 3299.99, unitWeightKg: 227.9, givenPriceKg: 11.30, defaultLaborHours: 1.3, defaultLaborRate: 2.75, defaultWastageKg: 4.5, defaultTwineKg: 0.85, defaultTwineRate: 6.64 },
  { code: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/16x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 2387.03, unitWeightKg: 164.85, givenPriceKg: 11.00, defaultLaborHours: 1.1, defaultLaborRate: 2.75, defaultWastageKg: 3.3, defaultTwineKg: 0.7, defaultTwineRate: 6.64 },
  { code: "NET-72-210-14-350", description: "No.72(210/14x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/14x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 2080.78, unitWeightKg: 143.7, givenPriceKg: 10.80, defaultLaborHours: 1.0, defaultLaborRate: 2.75, defaultWastageKg: 2.9, defaultTwineKg: 0.6, defaultTwineRate: 6.64 },
  { code: "NET-42-250-08-8IN", description: "No.42(250/08x16) 8\" Hi-Ex Braided Net", material: "Hi-Ex", plySize: "250D/08x16", meshSize: "8\"", meshDepth: "50md x 120fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 936.33, unitWeightKg: 33.9, givenPriceKg: 14.50, defaultLaborHours: 0.6, defaultLaborRate: 2.75, defaultWastageKg: 0.7, defaultTwineKg: 0.3, defaultTwineRate: 6.64 },
  { code: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", material: "Hi-Ex", plySize: "250D/20x16", meshSize: "5\"", meshDepth: "15md x 120fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 1063.98, unitWeightKg: 38.55, givenPriceKg: 14.00, defaultLaborHours: 0.65, defaultLaborRate: 2.75, defaultWastageKg: 0.8, defaultTwineKg: 0.32, defaultTwineRate: 6.64 },
  { code: "TWINE-HEX-TARRED", description: "H-Ex Lacing Twine, Tarred", material: "Hi-Ex", plySize: "—", meshSize: "—", meshDepth: "—", color: "Tarred", uom: "KGS", unitPrice: 6.64, unitWeightKg: 1, givenPriceKg: 5.10, defaultLaborHours: 0, defaultLaborRate: 0, defaultWastageKg: 0, defaultTwineKg: 0, defaultTwineRate: 0 },
];

// -------------------------------------------------------------------------
// Pricing rule engine — lookup tables and rule chain (Part A/C of the
// discovery doc). MD/DW/Insurance rows reuse the doc's own verified figures
// (122md -> +3.50, +10.00, net -> +0.66) so the engine is traceable back to
// the original simulation. Editable from Settings -> Pricing Rules.
// -------------------------------------------------------------------------
export const LOOKUP_TABLES: LookupTable[] = [
  {
    id: "lt_md",
    name: "Mesh Depth (MD) rate",
    rows: [
      { key: "122", value: 3.5 },
      { key: "50", value: 1.2 },
      { key: "15", value: 0.6 },
      { key: "default", value: 0 },
    ],
  },
  {
    id: "lt_dw",
    name: "Depth-Way (float length) rate",
    rows: [
      { key: "50", value: 10.0 },
      { key: "120", value: 6.5 },
      { key: "default", value: 0 },
    ],
  },
  {
    id: "lt_ins",
    name: "Insurance rate (by category)",
    rows: [
      { key: "net", value: 0.66 },
      { key: "twine", value: 0.18 },
      { key: "default", value: 0 },
    ],
  },
];

export const PRICING_RULES: PricingRule[] = [
  { id: "r_comm", code: "COMMISSION", label: "Commission", operation: "add", basis: "percent_of_result", rate: 3, sequence: 1, enabled: true },
  { id: "r_markup", code: "PERCENTAGE", label: "Markup", operation: "add", basis: "percent_of_base", rate: 5, sequence: 2, enabled: true },
  { id: "r_discount", code: "PERCENTAGE", label: "Discount", operation: "subtract", basis: "percent_of_base", rate: 5, sequence: 3, enabled: false },
  { id: "r_surcharge", code: "AMOUNT", label: "Flat surcharge", operation: "add", basis: "flat_amount", rate: 0.1, sequence: 4, enabled: false },
  { id: "r_deduction", code: "AMOUNT", label: "Flat deduction", operation: "subtract", basis: "flat_amount", rate: 0.2, sequence: 5, enabled: false },
  { id: "r_md", code: "MD_COMPUTATION", label: "Mesh Depth adjustment", operation: "add", basis: "lookup_table", rate: 0, lookupTableId: "lt_md", sequence: 6, enabled: true },
  { id: "r_dw", code: "DW_COMPUTATION", label: "Depth-Way adjustment", operation: "add", basis: "lookup_table", rate: 0, lookupTableId: "lt_dw", sequence: 7, enabled: true },
  { id: "r_ins", code: "INSURANCE", label: "Insurance", operation: "add", basis: "lookup_table", rate: 0, lookupTableId: "lt_ins", sequence: 8, enabled: true },
];

// -------------------------------------------------------------------------
// Helper to build a lifecycle stage array up to a given current stage.
// -------------------------------------------------------------------------
function buildStages(
  currentStage: OrderStage,
  overrides: Partial<Record<OrderStage, Partial<StageRecord>>> = {}
): StageRecord[] {
  const currentIdx = ORDER_STAGES.findIndex((s) => s.id === currentStage);
  return ORDER_STAGES.map((s, idx) => {
    let status: StageRecord["status"] = "pending";
    if (idx < currentIdx) status = "completed";
    else if (idx === currentIdx) status = "in_progress";
    const base: StageRecord = {
      stage: s.id,
      status,
      responsibleRole: s.role,
    };
    return { ...base, ...(overrides[s.id] || {}) };
  });
}

// -------------------------------------------------------------------------
// Quotations
// -------------------------------------------------------------------------
export const QUOTATIONS: Quotation[] = [
  {
    id: "PI-33002",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-05-02", changedBy: "Grace Tan", note: "Initial issue" }],
    customerId: "CUST-006",
    consignee: "West Coast Marine Supply Inc.",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-05-02",
    paymentTerms: "50% DP, 50% before loading",
    moq: "2 pcs per spec",
    leadTimeWeeks: 6,
    estimatedShipmentDate: "2026-07-14",
    items: [
      { id: "L1", itemCode: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 4, unit: "PCS", unitPrice: 3498.37, weightKg: 966, totalPrice: 13993.48 },
      { id: "L2", itemCode: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 6, unit: "PCS", unitPrice: 2387.03, weightKg: 989.1, totalPrice: 14322.18 },
    ],
    freight: 0,
    discount: 0,
    tax: 0,
    depositPercent: 50,
    assignedSalesperson: "Grace Tan",
    salesOrderId: "SO-1041",
    remarks: "FOB Manila. Standard export packing.",
    approver: "Marcus Reyes",
    approvedDate: "2026-05-03",
  },
  {
    id: "PI-33005",
    revisionNo: 1,
    revisions: [
      { revisionNo: 0, date: "2026-05-20", changedBy: "Grace Tan", note: "Initial issue" },
      { revisionNo: 1, date: "2026-05-24", changedBy: "Grace Tan", note: "Adjusted mesh depth per factory counter-offer" },
    ],
    customerId: "CUST-003",
    consignee: "PT Samudra Jaring Nusantara",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-05-24",
    paymentTerms: "30% DP, 70% before loading",
    moq: "3 pcs per spec",
    leadTimeWeeks: 7,
    estimatedShipmentDate: "2026-07-30",
    items: [
      { id: "L1", itemCode: "NET-72-210-14-350", description: "No.72(210/14x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 5, unit: "PCS", unitPrice: 2080.78, weightKg: 1437, totalPrice: 10403.90 },
      { id: "L3", itemCode: "NET-42-250-08-8IN", description: "No.42(250/08x16) 8\" Hi-Ex Braided Net", specification: "50md x 120fl (1066ml)", qtyPcs: 12, unit: "PCS", unitPrice: 936.33, weightKg: 406.8, totalPrice: 11235.96 },
    ],
    freight: 850,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    salesOrderId: "SO-1044",
    remarks: "FOB Manila.",
    approver: "Grace Tan",
    approvedDate: "2026-05-25",
  },
  {
    id: "PI-33009",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-06-18", changedBy: "Marcus Reyes", note: "Initial issue" }],
    customerId: "CUST-002",
    consignee: "Nordfisk Trading AS",
    status: "sent",
    currency: "USD",
    validityDays: 10,
    issueDate: "2026-06-18",
    paymentTerms: "30% DP, 70% before loading",
    moq: "2 pcs per spec",
    leadTimeWeeks: 6,
    estimatedShipmentDate: "2026-08-20",
    items: [
      { id: "L1", itemCode: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", specification: "15md x 120fl", qtyPcs: 8, unit: "PCS", unitPrice: 1063.98, weightKg: 308.4, totalPrice: 8511.84 },
    ],
    freight: 420,
    discount: 150,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    remarks: "Awaiting customer response. Follow-up scheduled.",
  },
  {
    id: "PI-33011",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-07-08", changedBy: "Grace Tan", note: "Initial issue" }],
    customerId: "CUST-004",
    consignee: "Golden Reef Fisheries Ltd.",
    status: "for_approval",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-07-08",
    paymentTerms: "40% DP, 60% before loading",
    moq: "3 pcs per spec",
    leadTimeWeeks: 8,
    estimatedShipmentDate: "2026-09-10",
    items: [
      { id: "L1", itemCode: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", specification: "122md x 40fl (946ml)", qtyPcs: 6, unit: "PCS", unitPrice: 2387.03, weightKg: 989.1, totalPrice: 14322.18 },
      { id: "L2", itemCode: "TWINE-HEX-TARRED", description: "H-Ex Lacing Twine, Tarred", specification: "Tarred, 6mm", qtyPcs: 320, unit: "KGS", unitPrice: 6.64, weightKg: 320, totalPrice: 2124.80 },
    ],
    freight: 0,
    discount: 0,
    tax: 0,
    depositPercent: 40,
    assignedSalesperson: "Grace Tan",
    remarks: "Pending Sales Manager approval — first order for this customer, credit terms to confirm.",
  },
  {
    id: "PI-33012",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-07-22", changedBy: "Marcus Reyes", note: "Initial issue, per Fortune Net & Twine reference PI #33007" }],
    customerId: "CUST-001",
    consignee: "KTI Company Limited",
    status: "draft",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-07-22",
    paymentTerms: "20% deposit, 80% before shipment",
    moq: "1 pc per spec",
    leadTimeWeeks: 8,
    estimatedShipmentDate: "2026-11-19",
    items: [
      { id: "L1", itemCode: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 2, unit: "PCS", unitPrice: 3498.37, weightKg: 483, totalPrice: 6996.74 },
      { id: "L2", itemCode: "NET-96-210-20-350", description: "No.96(210/20x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 2, unit: "PCS", unitPrice: 3299.99, weightKg: 455.8, totalPrice: 6599.98 },
      { id: "L3", itemCode: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 3, unit: "PCS", unitPrice: 2387.03, weightKg: 989.1, totalPrice: 7161.09 },
    ],
    freight: 0,
    discount: 0,
    tax: 0,
    depositPercent: 20,
    assignedSalesperson: "Marcus Reyes",
    remarks: "Reur email inquiry dated July 16, 2026. NPD 2612. Not yet submitted.",
  },
  {
    id: "PI-32994",
    revisionNo: 2,
    revisions: [
      { revisionNo: 0, date: "2026-04-02", changedBy: "Grace Tan", note: "Initial issue" },
      { revisionNo: 1, date: "2026-04-09", changedBy: "Grace Tan", note: "Quantity revised down per customer request" },
      { revisionNo: 2, date: "2026-04-15", changedBy: "Grace Tan", note: "Final pricing locked after negotiation" },
    ],
    customerId: "CUST-005",
    consignee: "Pacífico Redes S.A. de C.V.",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-04-15",
    paymentTerms: "30% DP, 70% before loading",
    moq: "2 pcs per spec",
    leadTimeWeeks: 5,
    estimatedShipmentDate: "2026-06-02",
    items: [
      { id: "L1", itemCode: "NET-72-210-14-350", description: "No.72(210/14x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 3, unit: "PCS", unitPrice: 2080.78, weightKg: 862.2, totalPrice: 6242.34 },
    ],
    freight: 300,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Grace Tan",
    salesOrderId: "SO-1039",
    remarks: "Completed order — reference for repeat business.",
    approver: "Marcus Reyes",
    approvedDate: "2026-04-16",
  },
  {
    id: "PI-33007-R1",
    revisionNo: 1,
    revisions: [
      { revisionNo: 0, date: "2026-06-30", changedBy: "Marcus Reyes", note: "Initial issue" },
      { revisionNo: 1, date: "2026-07-09", changedBy: "Marcus Reyes", note: "Customer requested minimum quantity clause on #210(42x16), 5\" selvage" },
    ],
    customerId: "CUST-007",
    consignee: "Senegal Peche Atlantique",
    status: "under_negotiation",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-07-09",
    paymentTerms: "30% DP, 70% before loading",
    moq: "1 pc minimum on selvage items",
    leadTimeWeeks: 9,
    estimatedShipmentDate: "2026-09-25",
    items: [
      { id: "L1", itemCode: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", specification: "15md x 120fl", qtyPcs: 4, unit: "PCS", unitPrice: 1063.98, weightKg: 154.2, totalPrice: 4255.92 },
    ],
    freight: 610,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    remarks: "Customer negotiating selvage length minimums to avoid short-length joins.",
    customerResponseNote: "Customer requests standard selvage length be guaranteed in writing before acceptance.",
  },
];

// -------------------------------------------------------------------------
// Sales Orders — covering the required demo scenarios
// -------------------------------------------------------------------------
export const SALES_ORDERS: SalesOrder[] = [
  {
    id: "SO-1041",
    quotationId: "PI-33002",
    customerId: "CUST-006",
    consignee: "West Coast Marine Supply Inc.",
    country: "United States",
    currency: "USD",
    orderValue: 28315.66,
    orderDate: "2026-05-04",
    requestedDeliveryDate: "2026-07-14",
    currentStage: "completed",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "completed",
    productionQtyOrdered: 10,
    productionQtyCompleted: 10,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-06-20",
    actualCompletionDate: "2026-06-18",
    invoiceId: "CI-9041",
    stages: buildStages("completed", {
      quotation: { status: "completed", completedDate: "2026-05-03" },
      customer_confirmation: { status: "completed", completedDate: "2026-05-04" },
      internal_verification: { status: "completed", completedDate: "2026-05-05" },
      deposit: { status: "completed", completedDate: "2026-05-08" },
      production: { status: "completed", completedDate: "2026-06-18" },
      packing: { status: "completed", completedDate: "2026-06-25" },
      inspection: { status: "completed", completedDate: "2026-06-28" },
      shipment: { status: "completed", completedDate: "2026-07-14" },
      final_payment: { status: "completed", completedDate: "2026-07-10" },
      documents: { status: "completed", completedDate: "2026-07-15" },
      completed: { status: "completed", completedDate: "2026-07-15" },
    }),
  },
  {
    id: "SO-1044",
    quotationId: "PI-33005",
    customerId: "CUST-003",
    consignee: "PT Samudra Jaring Nusantara",
    country: "Indonesia",
    currency: "USD",
    orderValue: 21639.86,
    orderDate: "2026-05-26",
    requestedDeliveryDate: "2026-07-30",
    currentStage: "shipment",
    priority: "high",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "completed",
    productionQtyOrdered: 17,
    productionQtyCompleted: 17,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-07-10",
    actualCompletionDate: "2026-07-09",
    stages: buildStages("shipment", {
      quotation: { status: "completed", completedDate: "2026-05-25" },
      customer_confirmation: { status: "completed", completedDate: "2026-05-26" },
      internal_verification: { status: "completed", completedDate: "2026-05-27" },
      deposit: { status: "completed", completedDate: "2026-05-30" },
      production: { status: "completed", completedDate: "2026-07-09" },
      packing: { status: "completed", completedDate: "2026-07-16" },
      inspection: { status: "completed", completedDate: "2026-07-19" },
      shipment: {
        status: "blocked",
        responsibleRole: "Logistics",
        pendingAction: "Remaining balance must clear before container loading",
        blocker: "Remaining balance (70%) not yet verified by Finance",
      },
    }),
  },
  {
    id: "SO-1039",
    quotationId: "PI-32994",
    customerId: "CUST-005",
    consignee: "Pacífico Redes S.A. de C.V.",
    country: "Mexico",
    currency: "USD",
    orderValue: 6542.34,
    orderDate: "2026-04-17",
    requestedDeliveryDate: "2026-06-02",
    currentStage: "completed",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "completed",
    productionQtyOrdered: 3,
    productionQtyCompleted: 3,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-05-20",
    actualCompletionDate: "2026-05-19",
    invoiceId: "CI-9039",
    stages: buildStages("completed", {
      quotation: { status: "completed", completedDate: "2026-04-16" },
      customer_confirmation: { status: "completed", completedDate: "2026-04-17" },
      internal_verification: { status: "completed", completedDate: "2026-04-18" },
      deposit: { status: "completed", completedDate: "2026-04-21" },
      production: { status: "completed", completedDate: "2026-05-19" },
      packing: { status: "completed", completedDate: "2026-05-24" },
      inspection: { status: "completed", completedDate: "2026-05-26" },
      shipment: { status: "completed", completedDate: "2026-06-02" },
      final_payment: { status: "completed", completedDate: "2026-05-30" },
      documents: { status: "completed", completedDate: "2026-06-03" },
      completed: { status: "completed", completedDate: "2026-06-03" },
    }),
  },
  {
    id: "SO-1046",
    quotationId: "PI-33011",
    customerId: "CUST-004",
    consignee: "Golden Reef Fisheries Ltd.",
    country: "Bangladesh",
    currency: "USD",
    orderValue: 16446.98,
    orderDate: "2026-07-10",
    requestedDeliveryDate: "2026-09-10",
    currentStage: "deposit",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "not_started",
    productionQtyOrdered: 6,
    productionQtyCompleted: 0,
    productionQtyRejected: 0,
    stages: buildStages("deposit", {
      quotation: { status: "completed", completedDate: "2026-07-08" },
      customer_confirmation: { status: "completed", completedDate: "2026-07-10" },
      internal_verification: { status: "completed", completedDate: "2026-07-11" },
      deposit: {
        status: "in_progress",
        responsibleRole: "Finance",
        pendingAction: "Verify 40% deposit against submitted remittance copy",
      },
    }),
  },
  {
    id: "SO-1047",
    quotationId: "PI-33005",
    customerId: "CUST-003",
    consignee: "PT Samudra Jaring Nusantara — repeat order",
    country: "Indonesia",
    currency: "USD",
    orderValue: 34120.5,
    orderDate: "2026-07-02",
    requestedDeliveryDate: "2026-09-01",
    currentStage: "production",
    priority: "high",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "in_production",
    productionQtyOrdered: 24,
    productionQtyCompleted: 14,
    productionQtyRejected: 1,
    plannedCompletionDate: "2026-08-10",
    stages: buildStages("production", {
      quotation: { status: "completed", completedDate: "2026-06-28" },
      customer_confirmation: { status: "completed", completedDate: "2026-07-01" },
      internal_verification: { status: "completed", completedDate: "2026-07-02" },
      deposit: { status: "completed", completedDate: "2026-07-05" },
      production: {
        status: "in_progress",
        responsibleRole: "Production",
        pendingAction: "Continue scheduled run — 14 of 24 pcs complete",
      },
    }),
  },
  {
    id: "SO-1048",
    quotationId: "PI-33009",
    customerId: "CUST-002",
    consignee: "Nordfisk Trading AS",
    country: "Norway",
    currency: "USD",
    orderValue: 25400,
    orderDate: "2026-07-15",
    requestedDeliveryDate: "2026-09-30",
    currentStage: "production",
    priority: "urgent",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "on_hold",
    productionQtyOrdered: 8,
    productionQtyCompleted: 2,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-08-05",
    delayReason: "Awaiting raw material restock for Hi-Ex 250D twine",
    stages: buildStages("production", {
      quotation: { status: "completed", completedDate: "2026-07-12" },
      customer_confirmation: { status: "completed", completedDate: "2026-07-14" },
      internal_verification: { status: "completed", completedDate: "2026-07-15" },
      deposit: { status: "completed", completedDate: "2026-07-17" },
      production: {
        status: "blocked",
        responsibleRole: "Production",
        pendingAction: "Resume production once raw material restock is confirmed",
        blocker: "Delayed 2 days — raw material shortage on Hi-Ex 250D twine",
      },
    }),
  },
  {
    id: "SO-1050",
    quotationId: "PI-33002",
    customerId: "CUST-006",
    consignee: "West Coast Marine Supply Inc. — Order 2",
    country: "United States",
    currency: "USD",
    orderValue: 19870,
    orderDate: "2026-07-20",
    requestedDeliveryDate: "2026-09-18",
    currentStage: "packing",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "completed",
    productionQtyOrdered: 9,
    productionQtyCompleted: 9,
    productionQtyRejected: 0,
    actualCompletionDate: "2026-07-28",
    stages: buildStages("packing", {
      quotation: { status: "completed", completedDate: "2026-07-18" },
      customer_confirmation: { status: "completed", completedDate: "2026-07-20" },
      internal_verification: { status: "completed", completedDate: "2026-07-21" },
      deposit: { status: "completed", completedDate: "2026-07-23" },
      production: { status: "completed", completedDate: "2026-07-28" },
      packing: {
        status: "in_progress",
        responsibleRole: "Logistics",
        pendingAction: "Awaiting customer confirmation of Tentative Packing List",
      },
    }),
  },
  {
    id: "SO-1051",
    quotationId: "PI-33005",
    customerId: "CUST-007",
    consignee: "Senegal Peche Atlantique",
    country: "Senegal",
    currency: "USD",
    orderValue: 4255.92,
    orderDate: "2026-07-26",
    requestedDeliveryDate: "2026-09-25",
    currentStage: "customer_confirmation",
    priority: "standard",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "not_started",
    productionQtyOrdered: 4,
    productionQtyCompleted: 0,
    productionQtyRejected: 0,
    stages: buildStages("customer_confirmation", {
      quotation: { status: "completed", completedDate: "2026-07-24" },
      customer_confirmation: {
        status: "in_progress",
        responsibleRole: "Sales",
        pendingAction: "Awaiting signed PO from customer",
      },
    }),
  },
];

// -------------------------------------------------------------------------
// Payments
// -------------------------------------------------------------------------
export const PAYMENTS: PaymentRecord[] = [
  { id: "PMT-5001", salesOrderId: "SO-1041", type: "deposit", expectedAmount: 14157.83, amountReceived: 14157.83, dateReceived: "2026-05-08", bankRef: "TT-KEB-88213", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-05-08", status: "verified" },
  { id: "PMT-5002", salesOrderId: "SO-1041", type: "balance", expectedAmount: 14157.83, amountReceived: 14157.83, dateReceived: "2026-07-10", bankRef: "TT-KEB-88940", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-07-10", status: "verified" },

  { id: "PMT-5003", salesOrderId: "SO-1044", type: "deposit", expectedAmount: 6491.96, amountReceived: 6491.96, dateReceived: "2026-05-30", bankRef: "TT-BCA-44120", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-05-30", status: "verified" },
  { id: "PMT-5004", salesOrderId: "SO-1044", type: "balance", expectedAmount: 15147.90, amountReceived: 0, status: "submitted_for_verification", dueDate: "2026-07-28", remarks: "Remittance copy uploaded by customer, awaiting bank confirmation." },

  { id: "PMT-5005", salesOrderId: "SO-1039", type: "deposit", expectedAmount: 1962.70, amountReceived: 1962.70, dateReceived: "2026-04-21", bankRef: "TT-SANT-11029", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-04-21", status: "verified" },
  { id: "PMT-5006", salesOrderId: "SO-1039", type: "balance", expectedAmount: 4579.64, amountReceived: 4579.64, dateReceived: "2026-05-30", bankRef: "TT-SANT-11190", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-05-30", status: "verified" },

  { id: "PMT-5007", salesOrderId: "SO-1046", type: "deposit", expectedAmount: 6578.79, amountReceived: 6578.79, dateReceived: "2026-07-24", bankRef: "TT-SCB-30021", method: "Wire Transfer", remittanceAttached: true, status: "submitted_for_verification", remarks: "First-time customer — Finance verification pending against bank statement." },
  { id: "PMT-5008", salesOrderId: "SO-1046", type: "balance", expectedAmount: 9868.19, amountReceived: 0, status: "expected", dueDate: "2026-08-25" },

  { id: "PMT-5009", salesOrderId: "SO-1047", type: "deposit", expectedAmount: 10236.15, amountReceived: 10236.15, dateReceived: "2026-07-05", bankRef: "TT-BCA-44550", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-07-06", status: "verified" },
  { id: "PMT-5010", salesOrderId: "SO-1047", type: "balance", expectedAmount: 23884.35, amountReceived: 0, status: "expected", dueDate: "2026-08-30" },

  { id: "PMT-5011", salesOrderId: "SO-1048", type: "deposit", expectedAmount: 7620, amountReceived: 7620, dateReceived: "2026-07-17", bankRef: "TT-DNB-90144", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-07-18", status: "verified" },
  { id: "PMT-5012", salesOrderId: "SO-1048", type: "balance", expectedAmount: 17780, amountReceived: 0, status: "overdue", dueDate: "2026-07-20", remarks: "Balance now overdue — hold discussed with Sales Manager." },

  { id: "PMT-5013", salesOrderId: "SO-1050", type: "deposit", expectedAmount: 9935, amountReceived: 9935, dateReceived: "2026-07-23", bankRef: "TT-CITI-77320", method: "Wire Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-07-23", status: "verified" },
  { id: "PMT-5014", salesOrderId: "SO-1050", type: "balance", expectedAmount: 9935, amountReceived: 3000, status: "partially_paid", dueDate: "2026-08-15", remarks: "Partial remittance received; balance short by $6,935.00." },

  { id: "PMT-5015", salesOrderId: "SO-1051", type: "deposit", expectedAmount: 1276.78, amountReceived: 0, status: "expected", dueDate: "2026-08-05" },
];

// -------------------------------------------------------------------------
// Commercial Invoices
// -------------------------------------------------------------------------
export const INVOICES: CommercialInvoice[] = [
  {
    id: "CI-9041",
    salesOrderId: "SO-1041",
    quotationId: "PI-33002",
    customerId: "CUST-006",
    issueDate: "2026-07-12",
    currency: "USD",
    items: QUOTATIONS.find((q) => q.id === "PI-33002")!.items,
    freight: 0,
    discount: 0,
    tax: 0,
    status: "paid",
    shippedWeightKg: 1955.1,
    billOfLadingNo: "MAEU-8821034",
    containerNo: "MSKU-4471820",
  },
  {
    id: "CI-9039",
    salesOrderId: "SO-1039",
    quotationId: "PI-32994",
    customerId: "CUST-005",
    issueDate: "2026-05-28",
    currency: "USD",
    items: QUOTATIONS.find((q) => q.id === "PI-32994")!.items,
    freight: 300,
    discount: 0,
    tax: 0,
    status: "paid",
    shippedWeightKg: 862.2,
    billOfLadingNo: "COSU-6620981",
    containerNo: "TCLU-2093841",
  },
];

// -------------------------------------------------------------------------
// Documents
// -------------------------------------------------------------------------
export const DOCUMENTS: DocRecord[] = [
  { id: "DOC-001", name: "PI-33002 Rev.0", type: "Proforma Invoice", relatedOrderId: "SO-1041", version: 1, uploadedBy: "Grace Tan", uploadDate: "2026-05-02", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-002", name: "PO-WCM-2205", type: "Purchase Order", relatedOrderId: "SO-1041", version: 1, uploadedBy: "Grace Tan", uploadDate: "2026-05-04", approvalStatus: "n/a", isCurrent: true },
  { id: "DOC-003", name: "CI-9041", type: "Commercial Invoice", relatedOrderId: "SO-1041", version: 1, uploadedBy: "Lourdes Ibarra", uploadDate: "2026-07-12", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-004", name: "PI-33005 Rev.0", type: "Proforma Invoice", relatedOrderId: "SO-1044", version: 1, uploadedBy: "Marcus Reyes", uploadDate: "2026-05-20", approvalStatus: "approved", isCurrent: false },
  { id: "DOC-005", name: "PI-33005 Rev.1", type: "Proforma Invoice", relatedOrderId: "SO-1044", version: 2, uploadedBy: "Marcus Reyes", uploadDate: "2026-05-24", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-006", name: "Tentative Packing List — SO-1044", type: "Packing List", relatedOrderId: "SO-1044", version: 1, uploadedBy: "Ronaldo Cruz", uploadDate: "2026-07-16", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-007", name: "Remittance Copy — Deposit SO-1046", type: "Remittance Copy", relatedOrderId: "SO-1046", version: 1, uploadedBy: "Golden Reef Fisheries Ltd.", uploadDate: "2026-07-24", approvalStatus: "pending", isCurrent: true },
  { id: "DOC-008", name: "Net Plan — Golden Reef 07-08-26", type: "Net Plan", relatedOrderId: "SO-1046", version: 1, uploadedBy: "Golden Reef Fisheries Ltd.", uploadDate: "2026-07-05", approvalStatus: "n/a", isCurrent: true },
  { id: "DOC-009", name: "Customer Confirmation Email — SO-1050 PL", type: "Customer Confirmation", relatedOrderId: "SO-1050", version: 1, uploadedBy: "West Coast Marine Supply Inc.", uploadDate: "2026-07-29", approvalStatus: "pending", isCurrent: true },
  { id: "DOC-010", name: "PI-33012 Draft", type: "Proforma Invoice", relatedOrderId: undefined, version: 1, uploadedBy: "Marcus Reyes", uploadDate: "2026-07-22", approvalStatus: "pending", isCurrent: true },
];

// -------------------------------------------------------------------------
// Approvals
// -------------------------------------------------------------------------
export const APPROVALS: ApprovalRequest[] = [
  {
    id: "APR-001",
    type: "PI Approval",
    referenceId: "PI-33011",
    customerId: "CUST-004",
    requestedBy: "Grace Tan",
    requestedDate: "2026-07-08",
    dueDate: "2026-07-31",
    level: "L2 Manager",
    status: "pending",
    reason: "New customer, first order — credit terms need Sales Manager sign-off.",
  },
  {
    id: "APR-002",
    type: "Payment Clearance",
    referenceId: "SO-1046",
    customerId: "CUST-004",
    requestedBy: "Lourdes Ibarra",
    requestedDate: "2026-07-24",
    dueDate: "2026-07-31",
    level: "L1 Supervisor",
    status: "pending",
    reason: "Verify 40% deposit remittance before releasing production.",
  },
  {
    id: "APR-003",
    type: "Loading Authorization",
    referenceId: "SO-1044",
    customerId: "CUST-003",
    requestedBy: "Ronaldo Cruz",
    requestedDate: "2026-07-27",
    dueDate: "2026-07-30",
    level: "L2 Manager",
    status: "pending",
    reason: "Container ready — blocked pending remaining balance verification.",
  },
  {
    id: "APR-004",
    type: "Discount Approval",
    referenceId: "PI-33009",
    customerId: "CUST-002",
    requestedBy: "Marcus Reyes",
    requestedDate: "2026-06-18",
    dueDate: "2026-07-02",
    level: "L2 Manager",
    status: "approved",
    reason: "$150 goodwill discount for repeat customer volume commitment.",
  },
  {
    id: "APR-005",
    type: "Sales Order Verification",
    referenceId: "SO-1048",
    customerId: "CUST-002",
    requestedBy: "Marcus Reyes",
    requestedDate: "2026-07-14",
    dueDate: "2026-07-16",
    level: "L1 Supervisor",
    status: "approved",
    reason: "Customer PO matched against production capability confirmation.",
  },
];

// -------------------------------------------------------------------------
// Activity log
// -------------------------------------------------------------------------
export const ACTIVITY: ActivityEntry[] = [
  { id: "ACT-001", timestamp: "2026-07-29T09:14:00+08:00", user: "West Coast Marine Supply Inc.", department: "Customer", action: "Uploaded packing list confirmation email", recordType: "Sales Order", recordId: "SO-1050", comment: "Customer confirmed quantities, requested container photo before loading." },
  { id: "ACT-002", timestamp: "2026-07-28T16:02:00+08:00", user: "Ronaldo Cruz", department: "Logistics", action: "Production completion recorded", previousStatus: "In Production", newStatus: "Completed", recordType: "Production Order", recordId: "SO-1050" },
  { id: "ACT-003", timestamp: "2026-07-27T11:40:00+08:00", user: "Ronaldo Cruz", department: "Logistics", action: "Requested loading authorization", recordType: "Sales Order", recordId: "SO-1044", comment: "Container packed, awaiting Finance clearance on remaining balance." },
  { id: "ACT-004", timestamp: "2026-07-26T08:55:00+08:00", user: "Marcus Reyes", department: "Sales", action: "Sales order created from accepted PI", previousStatus: "Quotation Accepted", newStatus: "Customer Confirmation", recordType: "Sales Order", recordId: "SO-1051" },
  { id: "ACT-005", timestamp: "2026-07-24T14:20:00+08:00", user: "Golden Reef Fisheries Ltd.", department: "Customer", action: "Remittance copy submitted for deposit", recordType: "Payment", recordId: "PMT-5007", comment: "40% deposit, TT reference TT-SCB-30021." },
  { id: "ACT-006", timestamp: "2026-07-22T10:05:00+08:00", user: "Marcus Reyes", department: "Sales", action: "Drafted new Proforma Invoice", recordType: "Quotation", recordId: "PI-33012" },
  { id: "ACT-007", timestamp: "2026-07-20T09:30:00+08:00", user: "Lourdes Ibarra", department: "Finance", action: "Verified deposit payment", previousStatus: "Submitted for Verification", newStatus: "Verified", recordType: "Payment", recordId: "PMT-5013" },
  { id: "ACT-008", timestamp: "2026-07-19T13:00:00+08:00", user: "System", department: "System", action: "Production delayed — raw material shortage flagged", previousStatus: "In Production", newStatus: "On Hold", recordType: "Sales Order", recordId: "SO-1048" },
  { id: "ACT-009", timestamp: "2026-07-16T15:44:00+08:00", user: "Ronaldo Cruz", department: "Logistics", action: "Tentative packing list submitted for internal review", recordType: "Sales Order", recordId: "SO-1044" },
  { id: "ACT-010", timestamp: "2026-07-09T09:12:00+08:00", user: "Marcus Reyes", department: "Sales", action: "PI Revision 1 issued", previousStatus: "Rev. 0", newStatus: "Rev. 1", recordType: "Quotation", recordId: "PI-33007-R1", comment: "Selvage length minimums under negotiation." },
  { id: "ACT-011", timestamp: "2026-07-08T11:02:00+08:00", user: "Grace Tan", department: "Sales", action: "Submitted PI for Sales Manager approval", previousStatus: "Draft", newStatus: "For Approval", recordType: "Quotation", recordId: "PI-33011" },
  { id: "ACT-012", timestamp: "2026-07-06T09:00:00+08:00", user: "Lourdes Ibarra", department: "Finance", action: "Verified deposit payment", previousStatus: "Submitted for Verification", newStatus: "Verified", recordType: "Payment", recordId: "PMT-5009" },
];

export const CURRENT_USER_BY_ROLE: Record<string, string> = {
  sales_rep: "Marcus Reyes",
  sales_manager: "Grace Tan",
  factory_technical: "Edwin Santos",
  finance: "Lourdes Ibarra",
  logistics: "Ronaldo Cruz",
  management: "Ma. Teresa Villanueva",
  admin: "System Administrator",
};
