import type {
  RoleInfo,
  Customer,
  ItemMaster,
  LookupTable,
  PricingRule,
  Quotation,
  SalesOrder,
  PaymentRecord,
  CommercialInvoice,
  DocRecord,
  ApprovalRequest,
  ActivityEntry,
  StageRecord,
  OrderStage,
} from "./types";
import { ORDER_STAGES } from "./types";

export const ROLES: RoleInfo[] = [
  {
    id: "sales_rep",
    label: "Sales Representative",
    department: "Sales",
    description: "Handles inquiries, quotations, and customer follow-up.",
  },
  {
    id: "sales_manager",
    label: "Sales Manager",
    department: "Sales",
    description: "Approves quotations, discounts, and order verification.",
  },
  {
    id: "factory_technical",
    label: "Factory Technical Team",
    department: "Technical",
    description: "Assesses feasibility and confirms production specs.",
  },
  {
    id: "finance",
    label: "Finance / Accounting",
    department: "Finance",
    description: "Verifies deposits, balances, and releases financial clearance.",
  },
  {
    id: "logistics",
    label: "Exportation / Logistics",
    department: "Logistics",
    description: "Books shipments and manages loading documentation.",
  },
  {
    id: "management",
    label: "Management",
    department: "Executive",
    description: "Oversight across the full order lifecycle.",
  },
  {
    id: "admin",
    label: "System Administrator",
    department: "Admin",
    description: "Full visibility for demonstration purposes.",
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: "CUST-001",
    name: "KTI Company Limited",
    consignee: "KTI Company Limited",
    country: "South Korea",
    address: "1503-8, Dadae-Dong, 49486 Saha-Gu, Busan, Korea",
    contactPerson: "Mr. Kevin Park",
    email: "purchase@ktigroup.co.kr",
    phone: "+82 51 264 0024",
    defaultPaymentTerms: "20% deposit, 80% before shipment",
    defaultCurrency: "USD",
    totalOrders: 14,
    totalValueUSD: 1284300,
    outstandingBalanceUSD: 146940.26,
    since: "2019-03-11",
    letterhead: "FORTUNE NET & TWINE MFG. CORP.",
    agent: "HOUSE ACCOUNT",
  },
  {
    id: "CUST-002",
    name: "Nordfisk Trading AS",
    consignee: "Nordfisk Trading AS",
    country: "Norway",
    address: "Skolegata 14, 6003 Ålesund, Norway",
    contactPerson: "Ms. Ingrid Solberg",
    email: "ingrid.solberg@nordfisk.no",
    phone: "+47 70 12 55 40",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 6,
    totalValueUSD: 402100,
    outstandingBalanceUSD: 0,
    since: "2021-06-02",
  },
  {
    id: "CUST-003",
    name: "PT Samudra Jaring Nusantara",
    consignee: "PT Samudra Jaring Nusantara",
    country: "Indonesia",
    address: "Jl. Perikanan No. 22, Muara Baru, Jakarta Utara",
    contactPerson: "Mr. Budi Hartono",
    email: "budi.hartono@samudrajaring.co.id",
    phone: "+62 21 6660 8812",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 9,
    totalValueUSD: 587250,
    outstandingBalanceUSD: 58210.4,
    since: "2020-01-19",
  },
  {
    id: "CUST-004",
    name: "Golden Reef Fisheries Ltd.",
    consignee: "Golden Reef Fisheries Ltd. / c/o Chittagong Freight Fwd.",
    country: "Bangladesh",
    address: "Agrabad Commercial Area, Chittagong 4100",
    contactPerson: "Mr. Rafiq Ahmed",
    email: "rafiq@goldenreef.com.bd",
    phone: "+880 31 251 4402",
    defaultPaymentTerms: "40% DP, 60% before loading",
    defaultCurrency: "USD",
    totalOrders: 4,
    totalValueUSD: 198400,
    outstandingBalanceUSD: 71460,
    since: "2023-02-14",
  },
  {
    id: "CUST-005",
    name: "Pacífico Redes S.A. de C.V.",
    consignee: "Pacífico Redes S.A. de C.V.",
    country: "Mexico",
    address: "Blvd. Marina Sur 341, Mazatlán, Sinaloa",
    contactPerson: "Sr. Alejandro Ruiz",
    email: "aruiz@pacificoredes.mx",
    phone: "+52 669 981 2230",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 3,
    totalValueUSD: 121600,
    outstandingBalanceUSD: 0,
    since: "2024-05-08",
  },
  {
    id: "CUST-006",
    name: "West Coast Marine Supply Inc.",
    consignee: "West Coast Marine Supply Inc.",
    country: "United States",
    address: "1180 Fisherman's Wharf Rd, San Pedro, CA 90731",
    contactPerson: "Mr. Daniel Cruz",
    email: "dcruz@wcmarinesupply.com",
    phone: "+1 310 555 0148",
    defaultPaymentTerms: "50% DP, 50% before loading",
    defaultCurrency: "USD",
    totalOrders: 11,
    totalValueUSD: 843900,
    outstandingBalanceUSD: 22150,
    since: "2018-09-27",
  },
  {
    id: "CUST-007",
    name: "Senegal Peche Atlantique",
    consignee: "Senegal Peche Atlantique",
    country: "Senegal",
    address: "Route de la Corniche, Dakar",
    contactPerson: "M. Ousmane Diallo",
    email: "o.diallo@pecheatlantique.sn",
    phone: "+221 33 842 1190",
    defaultPaymentTerms: "30% DP, 70% before loading",
    defaultCurrency: "USD",
    totalOrders: 2,
    totalValueUSD: 76800,
    outstandingBalanceUSD: 53760,
    since: "2025-01-30",
  },
  // ---- Imported from the export client master (real accounts, no order history in this prototype) ----
  { id: "CUST-008", name: "Alphatex", consignee: "Alphatex", country: "France", address: "Le Gite Bernard, 76490 Saint Wandrille Rancon, France", contactPerson: "Mr. Paul Lemonnier", email: "china.office2@alphatex.eu", phone: "+003 323 270 4265", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Paul Lemonnier", email: "china.office2@alphatex.eu", isPrimary: true }, { id: "c2", name: "Mr. Romain Chevalier" }, { id: "c3", name: "Mr. Kai Yao" }] },
  { id: "CUST-009", name: "ATS Nets & Ropes Pty. Ltd.", consignee: "ATS Nets & Ropes Pty. Ltd.", country: "Australia", address: "8 Brewer Street, Clontarf QLD 4019, Australia", contactPerson: "Mr. Jason Geraghty", email: "jason@atsnetsropes.com.au", phone: "+07 3284 1199", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-010", name: "Alshark For Import & Export Co., Ltd.", consignee: "Alshark For Import & Export Co., Ltd.", country: "Egypt", address: "6 Oct. Str, Borg Elbroloss, Kafr Elshikh, Egypt", contactPerson: "Mr. Kassem Mostafa Sharshir", email: "kasimsarsid@gmail.com", phone: "+002 012 736 5955", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "FORTUNE NET & TWINE MFG. CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-011", name: "Australian Southern Exporters", consignee: "Australian Southern Exporters", country: "Australia", address: "21 Pine Freezers Rd, Port Lincoln, South Australia 5606", contactPerson: "Ms. Anne Tapley", email: "info@challengefisheries.com.au", phone: "+0061 408 837139", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-012", name: "Breakwater Fishing Products", consignee: "Breakwater Fishing Products", country: "Australia", address: "132-138 Panoramic Drive, Port Lincoln, South Australia 5606", contactPerson: "Mr. Nathan Fauser", email: "nathanandjulz@gmail.com", phone: "+61 409 451 082", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "FORTUNE NET & TWINE MFG. CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Nathan Fauser", email: "nathanandjulz@gmail.com", isPrimary: true }, { id: "c2", name: "Ms. Julie Fauser" }] },
  { id: "CUST-013", name: "Caroline Fisheries Corp., Inc.", consignee: "Caroline Fisheries Corp., Inc.", country: "Micronesia", address: "Dekehtik Port, Nett P.O. Box 7, Kolonia, Pohnpei, FM 96941", contactPerson: "Mr. Juan Carlos Munoz", email: "marko@cfctuna.com", phone: "+691 320 5791", defaultPaymentTerms: "100% TT upon confirmation of order", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Juan Carlos Munoz", email: "jcmunoz@cfctuna.com", isPrimary: true }, { id: "c2", name: "Mr. Marko Kamber", email: "marko@cfctuna.com" }] },
  { id: "CUST-014", name: "(CKS) Chye Khiang Seng (M) Sdn. Bhd.", consignee: "(CKS) Chye Khiang Seng (M) Sdn. Bhd.", country: "Malaysia", address: "Wisma C.K.S., 155 Jalan Kapar, P.O. Box 211, 41720 Klang, Selangor, Malaysia", contactPerson: "Mr. Chew Guan Ho", email: "byencks@gmail.com", phone: "+00 603 3341 3233", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Chew Guan Ho", isPrimary: true }, { id: "c2", name: "Ms. Bee Yen", email: "byencks@gmail.com" }] },
  { id: "CUST-015", name: "Casamar (Seychelles) Ltd.", consignee: "Casamar (Seychelles) Ltd.", country: "Seychelles", address: "P.O. Box 272, Victoria, Mahe, Seychelles", contactPerson: "Mr. David Fabien", email: "davejourdan6@gmail.com", phone: "+248 2710253", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-016", name: "Fitec International", consignee: "Fitec International", country: "United States", address: "3889 East Raines Rd, Memphis, TN 38118, U.S.A.", contactPerson: "Mr. Mark Hall", email: "markhall@fitecgroup.com", phone: "+00 1 901 366 9144", defaultPaymentTerms: "20% deposit, 80% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-017", name: "Grup El Remitger SL", consignee: "Grup El Remitger SL", country: "Spain", address: "Can Barneda s/n, Pol. Ind. Moli d'en Xec Nau 28, 08291 Ripollet, Barcelona, Spain", contactPerson: "Mr. Fausti Martinez", email: "fausti@elremitger.com", phone: "+00 349 3224 0000", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-018", name: "Haverford Brands Pty. Ltd.", consignee: "Haverford Brands Pty. Ltd.", country: "Australia", address: "Unit 7/1-13 Childs Road, Chipping Norton, NSW 2170, Australia", contactPerson: "Mr. Daniel Winney", email: "danielwinney@haverford.com.au", phone: "+00 612 9771 5288", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Daniel Winney", title: "Director", email: "danielwinney@haverford.com.au", isPrimary: true }, { id: "c2", name: "Mr. Mark Winney", email: "markwinney@haverford.com.au" }] },
  { id: "CUST-019", name: "I.F. (Thailand) Co. Ltd.", consignee: "I.F. (Thailand) Co. Ltd.", country: "Thailand", address: "1134/225 Prima Srinakharin Bldg. C, 1st Fl., Srinakharin Rd, Suan Luang, Bangkok 10250, Thailand", contactPerson: "Mr. Eric Laurenson", email: "eric@internetfrance-group.com", phone: "+00 662 327 6598", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Eric Laurenson", email: "eric@internetfrance-group.com", isPrimary: true }, { id: "c2", name: "Mr. Edward Laurenson", email: "edward@internetfrance-group.com" }] },
  { id: "CUST-020", name: "Internet France S.A.R.L.", consignee: "Internet France S.A.R.L.", country: "France", address: "745 Rue Du Marais, 62170 Estreelles, France", contactPerson: "Mr. Eric Laurenson", email: "eric@internetfrance-group.com", phone: "+003 03 2106 1808", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Eric Laurenson", email: "eric@internetfrance-group.com", isPrimary: true }, { id: "c2", name: "Mr. Edward Laurenson", email: "edward@internetfrance-group.com" }] },
  { id: "CUST-021", name: "Kinoshita Fishing Net Mfg. Co., Ltd.", consignee: "Kinoshita Fishing Net Mfg. Co., Ltd.", country: "Japan", address: "Harimakaito 1, Nishihazu-Cho, Nishio-Shi, Aichi 444-0703, Japan", contactPerson: "Mr. Takashi Tomokiyo", email: "tomokiyo@muketsu.co.jp", phone: "+0563 62 3111", defaultPaymentTerms: "100% TT against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Takashi Tomokiyo", email: "tomokiyo@muketsu.co.jp", isPrimary: true }, { id: "c2", name: "Mr. Mitsunori Kimura", email: "m.kimura@muketsu.co.jp" }] },
  { id: "CUST-022", name: "Mary Stores (PT Summer Jaya Bumi Lestari)", consignee: "Mary Stores (PT Summer Jaya Bumi Lestari)", country: "Sri Lanka", address: "214 Bankshall Street, Colombo 11, Sri Lanka", contactPerson: "Mr. Denny Leon", email: "denny66joe@yahoo.co.in", phone: "+00 941 1232 0913", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-023", name: "Marnikol Fisheries Pty., Ltd.", consignee: "Marnikol Fisheries Pty., Ltd.", country: "Australia", address: "PO Box 10, Port Lincoln, South Australia 5606", contactPerson: "Dr. Daryl Evans", email: "marnikol@bigpond.net.au", phone: "+08 8683 3900", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Dr. Daryl Evans", isPrimary: true }, { id: "c2", name: "Ms. Karen Scott" }] },
  { id: "CUST-024", name: "Nets Tasmania Pty. Ltd.", consignee: "Nets Tasmania Pty. Ltd.", country: "Australia", address: "172 Kermandie Road, Geeveston, Tasmania 7116, Australia", contactPerson: "Mr. Robert Bruce", email: "donsnets@bigpond.com", phone: "+00 613 6229 3348", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Robert Bruce", email: "donsnets@bigpond.com", isPrimary: true }, { id: "c2", name: "Mr. Don Latham", email: "donsnets1@bigpond.com" }, { id: "c3", name: "Mr. Steven Latham", email: "donsnets2@bigpond.com" }] },
  { id: "CUST-025", name: "OY Nerival Group AB", consignee: "OY Nerival Group AB", country: "Finland", address: "Nuotiopiha 1 A 8, FI-02600 Espoo, Finland", contactPerson: "Mr. Ilpo Tapani", email: "info@nerivalgroup.fi", phone: "+358 0 40 911 5631", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Ilpo Tapani", email: "info@nerivalgroup.fi", isPrimary: true }, { id: "c2", name: "Mr. Muni Lipsky", email: "munilipsky@yahoo.com" }] },
  { id: "CUST-026", name: "Southern Supplies", consignee: "Southern Supplies", country: "United States", address: "326 East Howard Ave., Biloxi, MS 39530, U.S.A.", contactPerson: "Mr. John Nguyen", email: "johnssc6801@yahoo.com", phone: "+001 228 435 4401", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. John Nguyen", email: "johnssc6801@yahoo.com", isPrimary: true }, { id: "c2", name: "Ms. Linda Nguyen", email: "sscjohn6801@yahoo.com" }] },
  { id: "CUST-027", name: "Sumipesca S.A.", consignee: "Sumipesca S.A.", country: "Spain", address: "Navalaldea, B2A, 20110 Pasai Donibane, Guipuzcoa, Spain", contactPerson: "Mr. Zuhaitz Gonzalez Gutierrez", email: "administracion@sumipesca.es", phone: "+00 34 943 513900", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Zuhaitz Gonzalez Gutierrez", email: "zuhaitz@sumipesca.es", isPrimary: true }, { id: "c2", name: "Ms. Eneritz Sistiaga Alcaraz" }] },
  { id: "CUST-028", name: "Trident Nets Pty Ltd.", consignee: "Trident Nets Pty Ltd.", country: "Australia", address: "25 Humphreys St, New Norfolk, Tasmania 7140, Australia", contactPerson: "Mr. Danny Farrow", email: "tridentnetsptyltd@bigpond.com", phone: "+00 613 6261 3400", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-029", name: "The Deckstore Pty Ltd.", consignee: "The Deckstore Pty Ltd.", country: "Australia", address: "39 Tingira Street, Portsmith, Cairns, Queensland 4870, Australia", contactPerson: "Ms. Theresa Lowe", email: "theresa@thedeckstore.com.au", phone: "+00 617 4035 1951", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-030", name: "Wakamatsu Trading Co., Ltd.", consignee: "Wakamatsu Trading Co., Ltd.", country: "Japan", address: "#501, 1-10, 3-Chome Hirano-machi, 541-0046 Chuoku, Osaka, Japan", contactPerson: "Mr. Shinobu Hirose", email: "hiroses@kcn.ne.jp", phone: "+81 6 6229 2151", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  { id: "CUST-031", name: "White Fisheries Enterprise", consignee: "White Fisheries Enterprise", country: "Australia", address: "Port Lincoln, South Australia 5606", contactPerson: "Mr. Paul Giblin", email: "whitefisheries1@bigpond.com", phone: "—", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT", contacts: [{ id: "c1", name: "Mr. Paul Giblin", email: "whitefisheries1@bigpond.com", isPrimary: true }, { id: "c2", name: "Mr. Verne Lindsay", email: "vklindsay1@bigpond.com" }] },
  { id: "CUST-032", name: "Fortune Net Group - Div. South America", consignee: "Fortune Net Group - Div. South America", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "HOUSE ACCOUNT" },
  // ---- INSUPES sub-accounts (FORTUNE NET GROUP - DIV. SOUTH AMERICA), Chile — shared agent contact ----
  { id: "CUST-033", name: "AL8 Trading Ltda.", consignee: "AL8 Trading Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-034", name: "Blumar S.A.", consignee: "Blumar S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-035", name: "Bruening S.A.", consignee: "Bruening S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-036", name: "Corpesca S.A.", consignee: "Corpesca S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-037", name: "Comercial Isla Lennox S.P.A.", consignee: "Comercial Isla Lennox S.P.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "55% deposit, 45% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-038", name: "Com. Chilean Surfish Ltda.", consignee: "Com. Chilean Surfish Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-039", name: "Columbia Trading S.A.", consignee: "Columbia Trading S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-040", name: "Euro Náutica", consignee: "Euro Náutica", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "25% deposit, 75% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-041", name: "Eric Letelier", consignee: "Eric Letelier", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-042", name: "Fimar Centro Sur S.P.A.", consignee: "Fimar Centro Sur S.P.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, balance by LC before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-043", name: "Fimar Chile Ltda.", consignee: "Fimar Chile Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "20% deposit, balance by LC before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-044", name: "Gandara Chile S.A.", consignee: "Gandara Chile S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-045", name: "Hinrichsen & Vasey Operaciones Ltda.", consignee: "Hinrichsen & Vasey Operaciones Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-046", name: "Insumos Pesqueros Ltda.", consignee: "Insumos Pesqueros Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-047", name: "Multivalores S.A.", consignee: "Multivalores S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-048", name: "Omega Seafoods Ltda.", consignee: "Omega Seafoods Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-049", name: "Prodinsa S.A.", consignee: "Prodinsa S.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "20% deposit, 80% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-050", name: "Redes, Cabos e Hilos S.P.A.", consignee: "Redes, Cabos e Hilos S.P.A.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "LC at sight, irrevocable & transferable", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-051", name: "Redes Nitto Chile Ltda.", consignee: "Redes Nitto Chile Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-052", name: "Sindicato (Caleta Papudo)", consignee: "Sindicato (Caleta Papudo)", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "50% deposit, 50% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-053", name: "Soc. Pesquera Saez Y Saez Ltda.", consignee: "Soc. Pesquera Saez Y Saez Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "50% deposit, 50% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-054", name: "Supply & Operation S.A.C.", consignee: "Supply & Operation S.A.C.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-055", name: "Terramar Pesca SPA.", consignee: "Terramar Pesca SPA.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "30% deposit, 70% against copy of shipping documents", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
  { id: "CUST-056", name: "Tradestar Importacao Ltda.", consignee: "Tradestar Importacao Ltda.", country: "Chile", address: "Coronel 2317, Dpto. 501, Providencia, Santiago, Chile", contactPerson: "Mr. Luis Alberto Luengo M.", email: "lluengo@fnetgroup.com", phone: "+56 9 9225 0105", defaultPaymentTerms: "25% deposit, 75% before shipment", defaultCurrency: "USD", totalOrders: 0, totalValueUSD: 0, outstandingBalanceUSD: 0, since: "2026-08-03", letterhead: "NETTEX MFG. AND EXPORT CORP.", agent: "INSUPES" },
];

// -------------------------------------------------------------------------
// Standard Shipment / Validity phrasing pulled from the export client master
// (real terms currently written by hand on every quotation) — kept as plain
// reference lists for now; wiring them into NewQuotation as suggestions is a
// follow-up once we confirm the phrasing should replace the numeric
// leadTimeWeeks/validityDays fields or sit alongside them.
// -------------------------------------------------------------------------
export const SHIPMENT_TERM_OPTIONS: string[] = [
  "7 days from receipt of deposit",
  "15 days from receipt of deposit",
  "30 days from receipt of deposit",
  "45 days from receipt of deposit",
  "60 days from receipt of deposit",
  "75 days from receipt of deposit",
  "90 days from receipt of deposit",
  "120 days from receipt of deposit",
  "150 days from receipt of deposit",
  "165 days from receipt of deposit",
  "180 days from receipt of deposit",
  "210 days from receipt of deposit",
  "7 days from receipt of LC",
  "15 days from receipt of LC",
  "30 days from receipt of LC",
  "45 days from receipt of LC",
  "60 days from receipt of LC",
  "75 days from receipt of LC",
  "90 days from receipt of LC",
  "120 days from receipt of LC",
  "150 days from receipt of LC",
  "165 days from receipt of LC",
  "180 days from receipt of LC",
  "210 days from receipt of LC",
];

export const VALIDITY_TERM_OPTIONS: string[] = [
  "7 days, thereafter subject to our final confirmation.",
  "Please confirm by return within today.",
];

export const ITEM_MASTER: ItemMaster[] = [
  { code: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/22x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 3498.37, unitWeightKg: 241.5, givenPriceKg: 11.60, defaultLaborHours: 1.4, defaultLaborRate: 2.75, defaultWastageKg: 4.8, defaultTwineKg: 0.9, defaultTwineRate: 6.64 },
  { code: "NET-96-210-20-350", description: "No.96(210/20x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/20x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 3299.99, unitWeightKg: 227.9, givenPriceKg: 11.30, defaultLaborHours: 1.3, defaultLaborRate: 2.75, defaultWastageKg: 4.5, defaultTwineKg: 0.85, defaultTwineRate: 6.64 },
  { code: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/16x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 2387.03, unitWeightKg: 164.85, givenPriceKg: 11.00, defaultLaborHours: 1.1, defaultLaborRate: 2.75, defaultWastageKg: 3.3, defaultTwineKg: 0.7, defaultTwineRate: 6.64 },
  { code: "NET-72-210-14-350", description: "No.72(210/14x16) 3-1/2\" Nylon Braided Net", material: "Nylon (PA)", plySize: "210D/14x16", meshSize: "3-1/2\"", meshDepth: "122md x 50fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 2080.78, unitWeightKg: 143.7, givenPriceKg: 10.80, defaultLaborHours: 1.0, defaultLaborRate: 2.75, defaultWastageKg: 2.9, defaultTwineKg: 0.6, defaultTwineRate: 6.64 },
  { code: "NET-42-250-08-8IN", description: "No.42(250/08x16) 8\" Hi-Ex Braided Net", material: "Hi-Ex", plySize: "250D/08x16", meshSize: "8\"", meshDepth: "50md x 120fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 936.33, unitWeightKg: 33.9, givenPriceKg: 14.50, defaultLaborHours: 0.6, defaultLaborRate: 2.75, defaultWastageKg: 0.7, defaultTwineKg: 0.3, defaultTwineRate: 6.64 },
  { code: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", material: "Hi-Ex", plySize: "250D/20x16", meshSize: "5\"", meshDepth: "15md x 120fl", color: "Predyed Black, Tarred", uom: "PCS", unitPrice: 1063.98, unitWeightKg: 38.55, givenPriceKg: 14.00, defaultLaborHours: 0.65, defaultLaborRate: 2.75, defaultWastageKg: 0.8, defaultTwineKg: 0.32, defaultTwineRate: 6.64 },
  { code: "TWINE-HEX-TARRED", description: "H-Ex Lacing Twine, Tarred", material: "Hi-Ex", plySize: "—", meshSize: "—", meshDepth: "—", color: "Tarred", uom: "KGS", unitPrice: 6.64, unitWeightKg: 1, givenPriceKg: 5.10, defaultLaborHours: 0, defaultLaborRate: 0, defaultWastageKg: 0, defaultTwineKg: 0, defaultTwineRate: 0 },
];

// -------------------------------------------------------------------------
// Pricing rule engine — lookup tables and rule chain (Part A/C of the
// discovery doc). MD/DW/Insurance rows use the simulation doc's own observed
// figures so the engine is traceable back to the original run: §5.2 recorded
// 122MD -> +0.1750, DW (50FL) -> +0.5000, and insurance at 0.66% of the
// running total. Intermediate buckets interpolate linearly from those anchors
// (MD ~0.001434/md, DW 0.01/fl). Editable from Settings -> Pricing Rules.
// -------------------------------------------------------------------------
export const LOOKUP_TABLES: LookupTable[] = [
  {
    id: "lt_md",
    name: "Mesh Depth (MD) rate",
    valueKind: "amount",
    rows: [
      { key: "122", value: 0.175 }, // observed live, doc §5.2 row 6
      { key: "50", value: 0.072 },
      { key: "15", value: 0.022 },
      { key: "default", value: 0 },
    ],
  },
  {
    id: "lt_dw",
    name: "Depth-Way (float length) rate",
    valueKind: "amount",
    rows: [
      { key: "35", value: 0.35 },
      { key: "50", value: 0.5 }, // observed live, doc §5.2 row 7
      { key: "60", value: 0.6 },
      { key: "70", value: 0.7 },
      { key: "90", value: 0.9 },
      { key: "120", value: 1.2 },
      { key: "150", value: 1.5 },
      { key: "180", value: 1.8 },
      { key: "default", value: 0 },
    ],
  },
  {
    id: "lt_ins",
    name: "Insurance rate (by category)",
    // Percent, not currency — 0.66 means 0.66% of the running price per kg.
    valueKind: "percent",
    rows: [
      { key: "net", value: 0.66 },
      { key: "twine", value: 0.18 },
      { key: "default", value: 0 },
    ],
  },
];

export const PRICING_RULES: PricingRule[] = [
  { id: "r_comm", code: "COMMISSION", label: "Commission", operation: "add", basis: "percent_of_result", rate: 3, sequence: 1, enabled: true },
  { id: "r_markup", code: "PERCENTAGE", label: "Markup", operation: "add", basis: "percent_of_base", rate: 5, sequence: 2, enabled: true },
  { id: "r_discount", code: "PERCENTAGE", label: "Discount", operation: "subtract", basis: "percent_of_base", rate: 5, sequence: 3, enabled: false },
  { id: "r_surcharge", code: "AMOUNT", label: "Flat surcharge", operation: "add", basis: "flat_amount", rate: 0.1, sequence: 4, enabled: false },
  { id: "r_deduction", code: "AMOUNT", label: "Flat deduction", operation: "subtract", basis: "flat_amount", rate: 0.2, sequence: 5, enabled: false },
  { id: "r_md", code: "MD_COMPUTATION", label: "Mesh Depth adjustment", operation: "add", basis: "lookup_table", rate: 0, lookupTableId: "lt_md", sequence: 6, enabled: true },
  { id: "r_dw", code: "DW_COMPUTATION", label: "Depth-Way adjustment", operation: "add", basis: "lookup_table", rate: 0, lookupTableId: "lt_dw", sequence: 7, enabled: true },
  { id: "r_ins", code: "INSURANCE", label: "Insurance", operation: "add", basis: "lookup_table", rate: 0, lookupTableId: "lt_ins", sequence: 8, enabled: true },
];

// -------------------------------------------------------------------------
// Helper to build a lifecycle stage array up to a given current stage.
// -------------------------------------------------------------------------
function buildStages(
  currentStage: OrderStage,
  overrides: Partial<Record<OrderStage, Partial<StageRecord>>> = {}
): StageRecord[] {
  const currentIdx = ORDER_STAGES.findIndex((s) => s.id === currentStage);
  return ORDER_STAGES.map((s, idx) => {
    let status: StageRecord["status"] = "pending";
    if (idx < currentIdx) status = "completed";
    else if (idx === currentIdx) status = "in_progress";
    const base: StageRecord = {
      stage: s.id,
      status,
      responsibleRole: s.role,
    };
    return { ...base, ...(overrides[s.id] || {}) };
  });
}

// -------------------------------------------------------------------------
// Quotations
// -------------------------------------------------------------------------
export const QUOTATIONS: Quotation[] = [
  {
    id: "PI-34101",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-04-14", changedBy: "Grace Tan", note: "Initial issue" }],
    customerId: "CUST-006",
    consignee: "West Coast Marine Supply Inc.",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-04-14",
    paymentTerms: "50% DP, 50% before loading",
    leadTimeWeeks: 8,
    estimatedShipmentDate: "2026-06-20",
    items: [
      { id: "L1", itemCode: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 5, unit: "PCS", unitPrice: 3498.37, weightKg: 1207.5, totalPrice: 17491.85 },
      { id: "L2", itemCode: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 5, unit: "PCS", unitPrice: 2387.03, weightKg: 824.25, totalPrice: 11935.15 },
    ],
    freight: 250,
    discount: 0,
    tax: 0,
    depositPercent: 50,
    assignedSalesperson: "Grace Tan",
    salesOrderId: "SO-2201",
    remarks: "FOB Manila. Standard export packing.",
    approver: "Marcus Reyes",
    approvedDate: "2026-04-16",
  },
  {
    id: "PI-34102",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-07-21", changedBy: "Marcus Reyes", note: "Initial issue" }],
    customerId: "CUST-003",
    consignee: "PT Samudra Jaring Nusantara",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-07-21",
    paymentTerms: "30% DP, 70% before loading",
    leadTimeWeeks: 7,
    estimatedShipmentDate: "2026-09-20",
    items: [
      { id: "L1", itemCode: "NET-72-210-14-350", description: "No.72(210/14x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 5, unit: "PCS", unitPrice: 2080.78, weightKg: 718.5, totalPrice: 10403.90 },
      { id: "L2", itemCode: "NET-42-250-08-8IN", description: "No.42(250/08x16) 8\" Hi-Ex Braided Net", specification: "50md x 120fl (1066ml)", qtyPcs: 10, unit: "PCS", unitPrice: 936.33, weightKg: 339.0, totalPrice: 9363.30 },
    ],
    freight: 700,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    salesOrderId: "SO-2203",
    remarks: "FOB Manila.",
    approver: "Grace Tan",
    approvedDate: "2026-07-24",
  },
  {
    id: "PI-34103",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-07-03", changedBy: "Grace Tan", note: "Initial issue" }],
    customerId: "CUST-004",
    consignee: "Golden Reef Fisheries Ltd. / c/o Chittagong Freight Fwd.",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-07-03",
    paymentTerms: "40% DP, 60% before loading",
    leadTimeWeeks: 8,
    estimatedShipmentDate: "2026-09-15",
    items: [
      { id: "L1", itemCode: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 6, unit: "PCS", unitPrice: 2387.03, weightKg: 989.10, totalPrice: 14322.18 },
      { id: "L2", itemCode: "TWINE-HEX-TARRED", description: "H-Ex Lacing Twine, Tarred", specification: "Tarred, 6mm", qtyPcs: 300, unit: "KGS", unitPrice: 6.64, weightKg: 300, totalPrice: 1992.00 },
    ],
    freight: 0,
    discount: 0,
    tax: 0,
    depositPercent: 40,
    assignedSalesperson: "Grace Tan",
    salesOrderId: "SO-2204",
    remarks: "Pending Sales Manager approval was already cleared at PI stage — first order for this customer, credit terms confirmed.",
    approver: "Ma. Teresa Villanueva",
    approvedDate: "2026-07-06",
  },
  {
    id: "PI-34104",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-05-20", changedBy: "Marcus Reyes", note: "Initial issue" }],
    customerId: "CUST-002",
    consignee: "Nordfisk Trading AS",
    status: "accepted",
    currency: "USD",
    validityDays: 10,
    issueDate: "2026-05-20",
    paymentTerms: "30% DP, 70% before loading",
    leadTimeWeeks: 6,
    estimatedShipmentDate: "2026-08-25",
    items: [
      { id: "L1", itemCode: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", specification: "15md x 120fl", qtyPcs: 8, unit: "PCS", unitPrice: 1063.98, weightKg: 308.4, totalPrice: 8511.84 },
    ],
    freight: 420,
    discount: 150,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    salesOrderId: "SO-2205",
    remarks: "$150 goodwill discount approved for repeat volume commitment. FOB Manila.",
    approver: "Grace Tan",
    approvedDate: "2026-05-23",
  },
  {
    id: "PI-34105",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-04-28", changedBy: "Grace Tan", note: "Initial issue" }],
    customerId: "CUST-005",
    consignee: "Pacífico Redes S.A. de C.V.",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-04-28",
    paymentTerms: "30% DP, 70% before loading",
    leadTimeWeeks: 6,
    estimatedShipmentDate: "2026-08-10",
    items: [
      { id: "L1", itemCode: "NET-72-210-14-350", description: "No.72(210/14x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 4, unit: "PCS", unitPrice: 2080.78, weightKg: 574.8, totalPrice: 8323.12 },
    ],
    freight: 300,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Grace Tan",
    salesOrderId: "SO-2206",
    remarks: "FOB Manila.",
    approver: "Marcus Reyes",
    approvedDate: "2026-05-01",
  },
  {
    id: "PI-34106",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-06-20", changedBy: "Grace Tan", note: "Initial issue, per repeat account reference PI-34101" }],
    customerId: "CUST-006",
    consignee: "West Coast Marine Supply Inc. — Order 2",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-06-20",
    paymentTerms: "50% DP, 50% before loading",
    leadTimeWeeks: 8,
    estimatedShipmentDate: "2026-08-20",
    items: [
      { id: "L1", itemCode: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 3, unit: "PCS", unitPrice: 3498.37, weightKg: 724.5, totalPrice: 10495.11 },
      { id: "L2", itemCode: "NET-96-210-20-350", description: "No.96(210/20x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 3, unit: "PCS", unitPrice: 3299.99, weightKg: 683.7, totalPrice: 9899.97 },
    ],
    freight: 0,
    discount: 0,
    tax: 0,
    depositPercent: 50,
    assignedSalesperson: "Grace Tan",
    salesOrderId: "SO-2207",
    remarks: "FOB Manila. Standard export packing.",
    approver: "Marcus Reyes",
    approvedDate: "2026-06-22",
  },
  {
    id: "PI-34107",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-06-01", changedBy: "Marcus Reyes", note: "Initial issue" }],
    customerId: "CUST-007",
    consignee: "Senegal Peche Atlantique",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-06-01",
    paymentTerms: "30% DP, 70% before loading",
    leadTimeWeeks: 6,
    estimatedShipmentDate: "2026-08-05",
    items: [
      { id: "L1", itemCode: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", specification: "15md x 120fl", qtyPcs: 4, unit: "PCS", unitPrice: 1063.98, weightKg: 154.2, totalPrice: 4255.92 },
    ],
    freight: 610,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    salesOrderId: "SO-2208",
    remarks: "FOB Manila.",
    approver: "Grace Tan",
    approvedDate: "2026-06-03",
  },
  {
    id: "PI-34108",
    revisionNo: 1,
    revisions: [
      { revisionNo: 0, date: "2026-06-10", changedBy: "Marcus Reyes", note: "Initial issue" },
      { revisionNo: 1, date: "2026-06-15", changedBy: "Marcus Reyes", note: "Added lacing twine line per customer's follow-up request" },
    ],
    customerId: "CUST-003",
    consignee: "PT Samudra Jaring Nusantara — repeat order",
    status: "accepted",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-06-15",
    paymentTerms: "30% DP, 70% before loading",
    leadTimeWeeks: 7,
    estimatedShipmentDate: "2026-08-15",
    items: [
      { id: "L1", itemCode: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 2, unit: "PCS", unitPrice: 3498.37, weightKg: 483.0, totalPrice: 6996.74 },
      { id: "L2", itemCode: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 4, unit: "PCS", unitPrice: 2387.03, weightKg: 659.4, totalPrice: 9548.12 },
      { id: "L3", itemCode: "TWINE-HEX-TARRED", description: "H-Ex Lacing Twine, Tarred", specification: "Tarred, 6mm", qtyPcs: 150, unit: "KGS", unitPrice: 6.64, weightKg: 150, totalPrice: 996.00 },
    ],
    freight: 350,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    salesOrderId: "SO-2209",
    remarks: "FOB Manila. Repeat account, terms as previous shipments.",
    approver: "Grace Tan",
    approvedDate: "2026-06-18",
  },
  {
    id: "PI-34109",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-05-01", changedBy: "Marcus Reyes", note: "Initial issue" }],
    customerId: "CUST-002",
    consignee: "Nordfisk Trading AS — Order 2",
    status: "accepted",
    currency: "USD",
    validityDays: 10,
    issueDate: "2026-05-01",
    paymentTerms: "30% DP, 70% before loading",
    leadTimeWeeks: 6,
    estimatedShipmentDate: "2026-08-28",
    items: [
      { id: "L1", itemCode: "NET-96-210-20-350", description: "No.96(210/20x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 4, unit: "PCS", unitPrice: 3299.99, weightKg: 911.6, totalPrice: 13199.96 },
      { id: "L2", itemCode: "NET-42-250-08-8IN", description: "No.42(250/08x16) 8\" Hi-Ex Braided Net", specification: "50md x 120fl (1066ml)", qtyPcs: 8, unit: "PCS", unitPrice: 936.33, weightKg: 271.2, totalPrice: 7490.64 },
    ],
    freight: 500,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    salesOrderId: "SO-2210",
    remarks: "FOB Manila.",
    approver: "Grace Tan",
    approvedDate: "2026-05-04",
  },
  {
    id: "PI-34110",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-08-08", changedBy: "Marcus Reyes", note: "Initial issue" }],
    customerId: "CUST-001",
    consignee: "KTI Company Limited",
    status: "draft",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-08-08",
    paymentTerms: "20% deposit, 80% before shipment",
    leadTimeWeeks: 8,
    estimatedShipmentDate: "2026-11-20",
    items: [
      { id: "L1", itemCode: "NET-120-210-22-350", description: "No.120(210/22x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 2, unit: "PCS", unitPrice: 3498.37, weightKg: 483.0, totalPrice: 6996.74 },
      { id: "L2", itemCode: "NET-96-210-20-350", description: "No.96(210/20x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 2, unit: "PCS", unitPrice: 3299.99, weightKg: 455.8, totalPrice: 6599.98 },
      { id: "L3", itemCode: "NET-84-210-16-350", description: "No.84(210/16x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 3, unit: "PCS", unitPrice: 2387.03, weightKg: 494.55, totalPrice: 7161.09 },
    ],
    freight: 0,
    discount: 0,
    tax: 0,
    depositPercent: 20,
    assignedSalesperson: "Marcus Reyes",
    remarks: "Reur email inquiry dated Aug 1, 2026. Not yet submitted.",
  },
  {
    id: "PI-34111",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-08-07", changedBy: "Grace Tan", note: "Initial issue" }],
    customerId: "CUST-004",
    consignee: "Golden Reef Fisheries Ltd. / c/o Chittagong Freight Fwd.",
    status: "for_approval",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-08-07",
    paymentTerms: "40% DP, 60% before loading",
    leadTimeWeeks: 8,
    estimatedShipmentDate: "2026-10-15",
    items: [
      { id: "L1", itemCode: "NET-42-250-08-8IN", description: "No.42(250/08x16) 8\" Hi-Ex Braided Net", specification: "50md x 120fl (1066ml)", qtyPcs: 10, unit: "PCS", unitPrice: 936.33, weightKg: 339.0, totalPrice: 9363.30 },
    ],
    freight: 200,
    discount: 100,
    tax: 0,
    depositPercent: 40,
    assignedSalesperson: "Grace Tan",
    remarks: "Pending Sales Manager approval — second order from a first-year customer, discount needs sign-off.",
  },
  {
    id: "PI-34112",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-07-29", changedBy: "Marcus Reyes", note: "Initial issue" }],
    customerId: "CUST-002",
    consignee: "Nordfisk Trading AS",
    status: "sent",
    currency: "USD",
    validityDays: 10,
    issueDate: "2026-07-29",
    paymentTerms: "30% DP, 70% before loading",
    leadTimeWeeks: 6,
    estimatedShipmentDate: "2026-10-05",
    items: [
      { id: "L1", itemCode: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", specification: "15md x 120fl", qtyPcs: 6, unit: "PCS", unitPrice: 1063.98, weightKg: 231.3, totalPrice: 6383.88 },
    ],
    freight: 380,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Marcus Reyes",
    remarks: "Awaiting customer response. Follow-up scheduled.",
  },
  {
    id: "PI-34113",
    revisionNo: 1,
    revisions: [
      { revisionNo: 0, date: "2026-07-18", changedBy: "Grace Tan", note: "Initial issue" },
      { revisionNo: 1, date: "2026-07-25", changedBy: "Grace Tan", note: "Freight re-quoted after customer asked for a named carrier" },
    ],
    customerId: "CUST-005",
    consignee: "Pacífico Redes S.A. de C.V.",
    status: "under_negotiation",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-07-25",
    paymentTerms: "30% DP, 70% before loading",
    leadTimeWeeks: 6,
    estimatedShipmentDate: "2026-10-10",
    items: [
      { id: "L1", itemCode: "NET-96-250-20-5IN", description: "No.96(250/20x16) 5\" Hi-Ex Braided Net", specification: "15md x 120fl", qtyPcs: 5, unit: "PCS", unitPrice: 1063.98, weightKg: 192.75, totalPrice: 5319.90 },
    ],
    freight: 610,
    discount: 0,
    tax: 0,
    depositPercent: 30,
    assignedSalesperson: "Grace Tan",
    remarks: "Customer wants the named carrier confirmed in writing before accepting.",
    customerResponseNote: "Customer requests confirmation of carrier and transit time before signing.",
  },
  {
    id: "PI-34114",
    revisionNo: 0,
    revisions: [{ revisionNo: 0, date: "2026-06-05", changedBy: "Miguel Santos", note: "Initial issue" }],
    customerId: "CUST-011",
    consignee: "Australian Southern Exporters",
    status: "rejected",
    currency: "USD",
    validityDays: 7,
    issueDate: "2026-06-05",
    paymentTerms: "50% deposit, 50% before shipment",
    leadTimeWeeks: 8,
    estimatedShipmentDate: "2026-08-01",
    items: [
      { id: "L1", itemCode: "NET-72-210-14-350", description: "No.72(210/14x16) 3-1/2\" Nylon Braided Net", specification: "122md x 50fl (1180ml)", qtyPcs: 3, unit: "PCS", unitPrice: 2080.78, weightKg: 431.1, totalPrice: 6242.34 },
    ],
    freight: 300,
    discount: 0,
    tax: 0,
    depositPercent: 50,
    assignedSalesperson: "Miguel Santos",
    remarks: "Lost to a local supplier on lead time.",
    customerResponseNote: "Awarded to a local supplier — our 8 weeks against their 3.",
  },
];

// -------------------------------------------------------------------------
// Sales Orders — covering every stage of the lifecycle
// -------------------------------------------------------------------------
export const SALES_ORDERS: SalesOrder[] = [
  // Raised straight from INQ-3102 on the customer's own PO. No quotation exists behind it: the PO
  // is the agreement, so the order skips Customer Confirmation and starts at Deposit.
  {
    id: "SO-2202",
    inquiryId: "INQ-3102",
    customerPoNo: "PO-88231",
    customerId: "CUST-001",
    consignee: "KTI Company Limited",
    country: "South Korea",
    currency: "USD",
    orderValue: 22400,
    orderDate: "2026-08-02",
    requestedDeliveryDate: "2026-10-10",
    currentStage: "deposit",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "not_started",
    productionQtyOrdered: 0,
    productionQtyCompleted: 0,
    productionQtyRejected: 0,
    stages: buildStages("deposit", {
      deposit: { pendingAction: "Awaiting 30% deposit against PO-88231" },
    }),
  },
  {
    id: "SO-2201",
    quotationId: "PI-34101",
    customerId: "CUST-006",
    consignee: "West Coast Marine Supply Inc.",
    country: "United States",
    currency: "USD",
    orderValue: 29677.00,
    orderDate: "2026-04-18",
    requestedDeliveryDate: "2026-07-10",
    currentStage: "completed",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "completed",
    productionQtyOrdered: 10,
    productionQtyCompleted: 10,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-06-08",
    actualCompletionDate: "2026-06-10",
    invoiceId: "CI-2201",
    stages: buildStages("completed", {
      quotation: { status: "completed", completedDate: "2026-04-16" },
      customer_confirmation: { status: "completed", completedDate: "2026-04-18" },
      deposit: { status: "completed", completedDate: "2026-04-24" },
      packing: { status: "completed", completedDate: "2026-06-14" },
      inspection: { status: "completed", completedDate: "2026-06-16" },
      final_payment: { status: "completed", completedDate: "2026-06-20" },
      shipment: { status: "completed", completedDate: "2026-06-24" },
      completed: { status: "completed", completedDate: "2026-07-12" },
    }),
  },
  {
    id: "SO-2203",
    quotationId: "PI-34102",
    customerId: "CUST-003",
    consignee: "PT Samudra Jaring Nusantara",
    country: "Indonesia",
    currency: "USD",
    orderValue: 20467.20,
    orderDate: "2026-07-25",
    requestedDeliveryDate: "2026-09-20",
    currentStage: "customer_confirmation",
    priority: "standard",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "not_started",
    productionQtyOrdered: 15,
    productionQtyCompleted: 0,
    productionQtyRejected: 0,
    stages: buildStages("customer_confirmation", {
      quotation: { status: "completed", completedDate: "2026-07-24" },
      customer_confirmation: {
        status: "in_progress",
        responsibleRole: "Sales",
        pendingAction: "Awaiting signed PO from customer",
      },
    }),
  },
  {
    id: "SO-2204",
    quotationId: "PI-34103",
    customerId: "CUST-004",
    consignee: "Golden Reef Fisheries Ltd. / c/o Chittagong Freight Fwd.",
    country: "Bangladesh",
    currency: "USD",
    orderValue: 16314.18,
    orderDate: "2026-07-07",
    requestedDeliveryDate: "2026-09-15",
    currentStage: "deposit",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "not_started",
    productionQtyOrdered: 6,
    productionQtyCompleted: 0,
    productionQtyRejected: 0,
    stages: buildStages("deposit", {
      quotation: { status: "completed", completedDate: "2026-07-06" },
      customer_confirmation: { status: "completed", completedDate: "2026-07-07" },
      deposit: {
        status: "in_progress",
        responsibleRole: "Finance",
        pendingAction: "Verify 40% deposit against submitted remittance copy",
      },
    }),
  },
  {
    id: "SO-2205",
    quotationId: "PI-34104",
    customerId: "CUST-002",
    consignee: "Nordfisk Trading AS",
    country: "Norway",
    currency: "USD",
    orderValue: 8781.84,
    orderDate: "2026-05-26",
    requestedDeliveryDate: "2026-08-25",
    currentStage: "packing",
    priority: "standard",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "in_production",
    productionQtyOrdered: 8,
    productionQtyCompleted: 5,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-08-15",
    stages: buildStages("packing", {
      quotation: { status: "completed", completedDate: "2026-05-23" },
      customer_confirmation: { status: "completed", completedDate: "2026-05-26" },
      deposit: { status: "completed", completedDate: "2026-05-30" },
      packing: {
        status: "in_progress",
        responsibleRole: "Logistics",
        pendingAction: "Raise the packing list — 5 of 8 pcs off the line so far",
      },
    }),
  },
  {
    id: "SO-2206",
    quotationId: "PI-34105",
    customerId: "CUST-005",
    consignee: "Pacífico Redes S.A. de C.V.",
    country: "Mexico",
    currency: "USD",
    orderValue: 8623.12,
    orderDate: "2026-05-04",
    requestedDeliveryDate: "2026-08-10",
    currentStage: "packing",
    priority: "urgent",
    assignedSalesperson: "Grace Tan",
    productionStatus: "on_hold",
    productionQtyOrdered: 4,
    productionQtyCompleted: 1,
    productionQtyRejected: 0,
    plannedCompletionDate: "2026-08-05",
    delayReason: "Awaiting raw material restock for nylon 210D/14x16",
    stages: buildStages("packing", {
      quotation: { status: "completed", completedDate: "2026-05-01" },
      customer_confirmation: { status: "completed", completedDate: "2026-05-04" },
      deposit: { status: "completed", completedDate: "2026-05-09" },
      packing: {
        status: "blocked",
        responsibleRole: "Logistics",
        pendingAction: "Raise the packing list once the raw material restock is confirmed",
        blocker: "Delayed — raw material shortage on nylon 210D/14x16",
      },
    }),
  },
  {
    id: "SO-2207",
    quotationId: "PI-34106",
    customerId: "CUST-006",
    consignee: "West Coast Marine Supply Inc. — Order 2",
    country: "United States",
    currency: "USD",
    orderValue: 20395.08,
    orderDate: "2026-06-25",
    requestedDeliveryDate: "2026-08-20",
    currentStage: "packing",
    priority: "standard",
    assignedSalesperson: "Grace Tan",
    productionStatus: "completed",
    productionQtyOrdered: 6,
    productionQtyCompleted: 6,
    productionQtyRejected: 0,
    actualCompletionDate: "2026-07-22",
    stages: buildStages("packing", {
      quotation: { status: "completed", completedDate: "2026-06-22" },
      customer_confirmation: { status: "completed", completedDate: "2026-06-25" },
      deposit: { status: "completed", completedDate: "2026-06-30" },
      packing: {
        status: "in_progress",
        responsibleRole: "Logistics",
        pendingAction: "Packing list open — one of two items fully packed",
      },
    }),
  },
  {
    id: "SO-2208",
    quotationId: "PI-34107",
    customerId: "CUST-007",
    consignee: "Senegal Peche Atlantique",
    country: "Senegal",
    currency: "USD",
    orderValue: 4865.92,
    orderDate: "2026-06-05",
    requestedDeliveryDate: "2026-08-05",
    currentStage: "inspection",
    priority: "high",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "completed",
    productionQtyOrdered: 4,
    productionQtyCompleted: 4,
    productionQtyRejected: 0,
    actualCompletionDate: "2026-07-15",
    stages: buildStages("inspection", {
      quotation: { status: "completed", completedDate: "2026-06-03" },
      customer_confirmation: { status: "completed", completedDate: "2026-06-05" },
      deposit: { status: "completed", completedDate: "2026-06-10" },
      packing: { status: "completed", completedDate: "2026-07-20" },
      inspection: {
        status: "in_progress",
        responsibleRole: "QC",
        pendingAction: "Weigh the packed goods and settle the order value",
      },
    }),
  },
  {
    id: "SO-2209",
    quotationId: "PI-34108",
    customerId: "CUST-003",
    consignee: "PT Samudra Jaring Nusantara — repeat order",
    country: "Indonesia",
    currency: "USD",
    orderValue: 17856.25,
    orderDate: "2026-06-20",
    requestedDeliveryDate: "2026-08-15",
    currentStage: "final_payment",
    priority: "high",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "completed",
    productionQtyOrdered: 6,
    productionQtyCompleted: 6,
    productionQtyRejected: 0,
    actualCompletionDate: "2026-07-18",
    stages: buildStages("final_payment", {
      quotation: { status: "completed", completedDate: "2026-06-18" },
      customer_confirmation: { status: "completed", completedDate: "2026-06-20" },
      deposit: { status: "completed", completedDate: "2026-06-25" },
      packing: { status: "completed", completedDate: "2026-07-23" },
      inspection: { status: "completed", completedDate: "2026-07-26" },
      final_payment: {
        status: "blocked",
        responsibleRole: "Finance",
        pendingAction: "Verify the balance against submitted remittance copy",
        blocker: "Container ready — loading blocked pending balance verification",
      },
    }),
  },
  {
    id: "SO-2210",
    quotationId: "PI-34109",
    customerId: "CUST-002",
    consignee: "Nordfisk Trading AS — Order 2",
    country: "Norway",
    currency: "USD",
    orderValue: 21190.60,
    orderDate: "2026-05-07",
    requestedDeliveryDate: "2026-08-30",
    currentStage: "shipment",
    priority: "standard",
    assignedSalesperson: "Marcus Reyes",
    productionStatus: "completed",
    productionQtyOrdered: 12,
    productionQtyCompleted: 12,
    productionQtyRejected: 0,
    actualCompletionDate: "2026-07-25",
    stages: buildStages("shipment", {
      quotation: { status: "completed", completedDate: "2026-05-04" },
      customer_confirmation: { status: "completed", completedDate: "2026-05-07" },
      deposit: { status: "completed", completedDate: "2026-05-12" },
      packing: { status: "completed", completedDate: "2026-07-29" },
      inspection: { status: "completed", completedDate: "2026-07-31" },
      final_payment: { status: "completed", completedDate: "2026-08-04" },
      shipment: {
        status: "in_progress",
        responsibleRole: "Logistics",
        pendingAction: "Container en route — raise documents on arrival",
      },
    }),
  },
];

// -------------------------------------------------------------------------
// Payments
// -------------------------------------------------------------------------
export const PAYMENTS: PaymentRecord[] = [
  { id: "PMT-6001", salesOrderId: "SO-2201", type: "deposit", expectedAmount: 14838.50, amountReceived: 14838.50, dateReceived: "2026-04-24", bankRef: "TT-CITI-77410", method: "Wire Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-04-24", status: "verified" },
  { id: "PMT-6002", salesOrderId: "SO-2201", type: "balance", expectedAmount: 14838.50, amountReceived: 14853.50, dateReceived: "2026-06-20", bankRef: "TT-CITI-78120", method: "Wire Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-06-20", status: "verified", remarks: "Customer rounded the transfer up; $15.00 recorded as overpayment." },
  { id: "PMT-6003", salesOrderId: "SO-2201", type: "adjustment", expectedAmount: 180.00, amountReceived: 0, status: "rejected", dueDate: "2026-06-25", remarks: "Customer's freight discrepancy claim — declined; freight was correctly charged per FOB Manila terms." },

  { id: "PMT-6004", salesOrderId: "SO-2202", type: "deposit", expectedAmount: 6720.00, amountReceived: 0, status: "expected", dueDate: "2026-08-16", remarks: "Against customer PO PO-88231, 30% deposit." },
  { id: "PMT-6005", salesOrderId: "SO-2202", type: "balance", expectedAmount: 15680.00, amountReceived: 0, status: "expected", dueDate: "2026-10-01" },

  { id: "PMT-6006", salesOrderId: "SO-2203", type: "deposit", expectedAmount: 6140.16, amountReceived: 0, status: "expected", dueDate: "2026-08-20" },
  { id: "PMT-6007", salesOrderId: "SO-2203", type: "balance", expectedAmount: 14327.04, amountReceived: 0, status: "expected", dueDate: "2026-09-15" },

  { id: "PMT-6008", salesOrderId: "SO-2204", type: "deposit", expectedAmount: 6525.67, amountReceived: 6525.67, dateReceived: "2026-07-29", bankRef: "TT-SCB-40021", method: "Wire Transfer", remittanceAttached: true, status: "submitted_for_verification", remarks: "First-time customer — Finance verification pending against bank statement." },
  { id: "PMT-6009", salesOrderId: "SO-2204", type: "balance", expectedAmount: 9788.51, amountReceived: 0, status: "expected", dueDate: "2026-09-10" },

  { id: "PMT-6010", salesOrderId: "SO-2205", type: "deposit", expectedAmount: 2634.55, amountReceived: 2634.55, dateReceived: "2026-05-30", bankRef: "TT-DNB-90210", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-05-30", status: "verified" },
  { id: "PMT-6011", salesOrderId: "SO-2205", type: "balance", expectedAmount: 6147.29, amountReceived: 0, status: "expected", dueDate: "2026-08-25" },
  {
    id: "PMT-6012",
    salesOrderId: "SO-2205",
    type: "adjustment",
    expectedAmount: 180.00,
    amountReceived: 0,
    status: "expected",
    approval: { state: "pending_approval", author: "Marcus Reyes", authoredDate: "2026-08-05", intendedApprover: "Grace Tan" },
    remarks: "Extra crating requested by customer, awaiting Sales Manager approval before invoicing.",
  },

  { id: "PMT-6013", salesOrderId: "SO-2206", type: "deposit", expectedAmount: 2586.94, amountReceived: 2586.94, dateReceived: "2026-05-09", bankRef: "TT-SANT-12040", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-05-09", status: "verified" },
  { id: "PMT-6014", salesOrderId: "SO-2206", type: "balance", expectedAmount: 6036.18, amountReceived: 0, status: "expected", dueDate: "2026-08-25" },

  { id: "PMT-6015", salesOrderId: "SO-2207", type: "deposit", expectedAmount: 10197.54, amountReceived: 10197.54, dateReceived: "2026-06-30", bankRef: "TT-CITI-77900", method: "Wire Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-06-30", status: "verified" },
  { id: "PMT-6016", salesOrderId: "SO-2207", type: "balance", expectedAmount: 10197.54, amountReceived: 4000.00, status: "partially_paid", dueDate: "2026-08-20", remarks: "Partial remittance received ahead of shipment; balance short by $6,197.54." },

  { id: "PMT-6017", salesOrderId: "SO-2208", type: "deposit", expectedAmount: 1459.78, amountReceived: 1459.78, dateReceived: "2026-06-10", bankRef: "TT-SANT-13010", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-06-10", status: "verified" },
  { id: "PMT-6018", salesOrderId: "SO-2208", type: "balance", expectedAmount: 3406.14, amountReceived: 0, status: "overdue", dueDate: "2026-08-01", remarks: "Balance now overdue — inspection still pending, hold discussed with Sales Manager." },

  { id: "PMT-6019", salesOrderId: "SO-2209", type: "deposit", expectedAmount: 5367.26, amountReceived: 5367.26, dateReceived: "2026-06-25", bankRef: "TT-BCA-44810", method: "Telegraphic Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-06-25", status: "verified" },
  { id: "PMT-6020", salesOrderId: "SO-2209", type: "balance", expectedAmount: 12488.99, amountReceived: 12488.99, dateReceived: "2026-08-06", bankRef: "TT-BCA-45390", method: "Telegraphic Transfer", remittanceAttached: true, status: "submitted_for_verification", remarks: "Remittance copy uploaded by customer, awaiting bank confirmation. Amount restated after inspection settled the order value." },

  { id: "PMT-6021", salesOrderId: "SO-2210", type: "deposit", expectedAmount: 6357.18, amountReceived: 6357.18, dateReceived: "2026-05-12", bankRef: "TT-DNB-90055", method: "Wire Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-05-12", status: "verified" },
  { id: "PMT-6022", salesOrderId: "SO-2210", type: "balance", expectedAmount: 14833.42, amountReceived: 14833.42, dateReceived: "2026-08-04", bankRef: "TT-DNB-91820", method: "Wire Transfer", remittanceAttached: true, verifiedBy: "Lourdes Ibarra", verificationDate: "2026-08-04", status: "verified" },
];

// -------------------------------------------------------------------------
// Commercial Invoices
// -------------------------------------------------------------------------
export const INVOICES: CommercialInvoice[] = [
  {
    id: "CI-2201",
    salesOrderId: "SO-2201",
    quotationId: "PI-34101",
    customerId: "CUST-006",
    issueDate: "2026-06-24",
    currency: "USD",
    items: QUOTATIONS.find((q) => q.id === "PI-34101")!.items,
    freight: 250,
    discount: 0,
    tax: 0,
    status: "paid",
    shippedWeightKg: 2031.75,
    billOfLadingNo: "MAEU-8830210",
    containerNo: "MSKU-4498210",
  },
];

// -------------------------------------------------------------------------
// Documents
// -------------------------------------------------------------------------
export const DOCUMENTS: DocRecord[] = [
  { id: "DOC-101", name: "PI-34101 Rev.0", type: "Proforma Invoice", relatedOrderId: "SO-2201", version: 1, uploadedBy: "Grace Tan", uploadDate: "2026-04-14", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-102", name: "Customer Confirmation Email — SO-2201", type: "Customer Confirmation", relatedOrderId: "SO-2201", version: 1, uploadedBy: "West Coast Marine Supply Inc.", uploadDate: "2026-04-18", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-103", name: "CI-2201", type: "Commercial Invoice", relatedOrderId: "SO-2201", version: 1, uploadedBy: "Lourdes Ibarra", uploadDate: "2026-06-24", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-104", name: "PO-88231-KTI.pdf", type: "Purchase Order", relatedOrderId: "SO-2202", version: 1, uploadedBy: "Grace Tan", uploadDate: "2026-08-02", approvalStatus: "n/a", isCurrent: true },
  { id: "DOC-105", name: "PI-34108 Rev.0", type: "Proforma Invoice", relatedOrderId: "SO-2209", version: 1, uploadedBy: "Marcus Reyes", uploadDate: "2026-06-10", approvalStatus: "approved", isCurrent: false },
  { id: "DOC-106", name: "PI-34108 Rev.1", type: "Proforma Invoice", relatedOrderId: "SO-2209", version: 2, uploadedBy: "Marcus Reyes", uploadDate: "2026-06-15", approvalStatus: "approved", isCurrent: true },
  { id: "DOC-107", name: "Tentative Packing List — SO-2207", type: "Packing List", relatedOrderId: "SO-2207", version: 1, uploadedBy: "Ronaldo Cruz", uploadDate: "2026-08-01", approvalStatus: "pending", isCurrent: true },
  { id: "DOC-108", name: "Remittance Copy — Deposit SO-2204", type: "Remittance Copy", relatedOrderId: "SO-2204", version: 1, uploadedBy: "Golden Reef Fisheries Ltd.", uploadDate: "2026-07-30", approvalStatus: "pending", isCurrent: true },
  { id: "DOC-109", name: "Net Plan — Golden Reef 08-02-26", type: "Net Plan", relatedOrderId: undefined, version: 1, uploadedBy: "Golden Reef Fisheries Ltd.", uploadDate: "2026-08-02", approvalStatus: "n/a", isCurrent: true },
  { id: "DOC-110", name: "PI-34112 Draft", type: "Proforma Invoice", relatedOrderId: undefined, version: 1, uploadedBy: "Marcus Reyes", uploadDate: "2026-07-29", approvalStatus: "pending", isCurrent: true },
];

// -------------------------------------------------------------------------
// Approvals
// -------------------------------------------------------------------------
export const APPROVALS: ApprovalRequest[] = [
  {
    id: "APR-101",
    type: "PI Approval",
    referenceId: "PI-34111",
    customerId: "CUST-004",
    requestedBy: "Grace Tan",
    requestedDate: "2026-08-07",
    dueDate: "2026-08-14",
    level: "L2 Manager",
    status: "pending",
    reason: "Second order from a first-year customer — discount needs Sales Manager sign-off.",
  },
  {
    id: "APR-102",
    type: "Payment Clearance",
    referenceId: "SO-2204",
    customerId: "CUST-004",
    requestedBy: "Lourdes Ibarra",
    requestedDate: "2026-07-30",
    dueDate: "2026-08-06",
    level: "L1 Supervisor",
    status: "pending",
    reason: "Verify 40% deposit remittance before releasing production — first-time customer.",
  },
  {
    id: "APR-103",
    type: "Loading Authorization",
    referenceId: "SO-2209",
    customerId: "CUST-003",
    requestedBy: "Ronaldo Cruz",
    requestedDate: "2026-08-06",
    dueDate: "2026-08-09",
    level: "L2 Manager",
    status: "pending",
    reason: "Container ready — blocked pending final balance verification.",
  },
  {
    id: "APR-104",
    type: "Discount Approval",
    referenceId: "PI-34104",
    customerId: "CUST-002",
    requestedBy: "Marcus Reyes",
    requestedDate: "2026-05-18",
    dueDate: "2026-05-24",
    level: "L2 Manager",
    status: "approved",
    reason: "$150 goodwill discount for repeat customer volume commitment.",
  },
  {
    id: "APR-105",
    type: "Sales Order Verification",
    referenceId: "SO-2202",
    customerId: "CUST-001",
    requestedBy: "Grace Tan",
    requestedDate: "2026-08-02",
    dueDate: "2026-08-04",
    level: "L1 Supervisor",
    status: "approved",
    reason: "Customer PO matched against production capability confirmation.",
  },
];

// -------------------------------------------------------------------------
// Activity log
// -------------------------------------------------------------------------
export const ACTIVITY: ActivityEntry[] = [
  { id: "ACT-101", timestamp: "2026-08-09T14:20:00+08:00", user: "Marcus Reyes", department: "Sales", action: "PI Revision 1 issued", previousStatus: "Rev. 0", newStatus: "Rev. 1", recordType: "Quotation", recordId: "PI-34113", comment: "Freight re-quoted after customer asked for a named carrier." },
  { id: "ACT-102", timestamp: "2026-08-08T10:05:00+08:00", user: "Ronaldo Cruz", department: "Logistics", action: "Shipment departed", recordType: "Shipment", recordId: "SH-2210", comment: "Departed Manila, ETA 2026-08-28." },
  { id: "ACT-103", timestamp: "2026-08-06T16:40:00+08:00", user: "PT Samudra Jaring Nusantara", department: "Customer", action: "Remittance copy submitted for balance payment", recordType: "Payment", recordId: "PMT-6020", comment: "TT reference TT-BCA-45390." },
  { id: "ACT-104", timestamp: "2026-08-05T09:12:00+08:00", user: "Marcus Reyes", department: "Sales", action: "Raised adjustment for extra crating", recordType: "Sales Order", recordId: "SO-2205", comment: "$180.00, awaiting Sales Manager approval." },
  { id: "ACT-105", timestamp: "2026-08-04T11:00:00+08:00", user: "Grace Tan", department: "Sales", action: "Forwarded new inquiry to plant", recordType: "Customer Inquiry", recordId: "INQ-3107" },
  { id: "ACT-106", timestamp: "2026-08-02T15:30:00+08:00", user: "Grace Tan", department: "Sales", action: "Second inquiry logged", recordType: "Customer Inquiry", recordId: "INQ-3111" },
  { id: "ACT-107", timestamp: "2026-08-02T09:00:00+08:00", user: "Grace Tan", department: "Sales", action: "Sales order created from customer PO", previousStatus: "Direct Order", newStatus: "Deposit", recordType: "Sales Order", recordId: "SO-2202" },
  { id: "ACT-108", timestamp: "2026-08-01T13:15:00+08:00", user: "Ronaldo Cruz", department: "Logistics", action: "Packing list opened, partially packed", recordType: "Sales Order", recordId: "SO-2207" },
  { id: "ACT-109", timestamp: "2026-07-31T10:00:00+08:00", user: "Elena Vasquez", department: "QC", action: "Inspection passed", recordType: "Sales Order", recordId: "SO-2210", comment: "No defects. Released for balance invoicing." },
  { id: "ACT-110", timestamp: "2026-07-30T14:20:00+08:00", user: "Golden Reef Fisheries Ltd.", department: "Customer", action: "Remittance copy submitted for deposit", recordType: "Payment", recordId: "PMT-6008", comment: "40% deposit, TT reference TT-SCB-40021." },
  { id: "ACT-111", timestamp: "2026-07-26T11:00:00+08:00", user: "Elena Vasquez", department: "QC", action: "Inspection passed — order value settled", recordType: "Sales Order", recordId: "SO-2209", comment: "Actual weights applied; order value restated to $17,856.25." },
  { id: "ACT-112", timestamp: "2026-07-20T09:30:00+08:00", user: "System", department: "System", action: "Production delayed — raw material shortage flagged", previousStatus: "In Production", newStatus: "On Hold", recordType: "Sales Order", recordId: "SO-2206" },
];

export const CURRENT_USER_BY_ROLE: Record<string, string> = {
  sales_rep: "Marcus Reyes",
  sales_manager: "Grace Tan",
  factory_technical: "Edwin Santos",
  finance: "Lourdes Ibarra",
  logistics: "Ronaldo Cruz",
  management: "Ma. Teresa Villanueva",
  admin: "System Administrator",
};
